import {BrainCircuit,Check,GitBranch,MousePointer2,Network,Pencil,Plus,Save,Trash2,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {clampMindMapPosition,layoutMindMapNodes,mindMapRoot,removeMindMapBranch,type ClientMindMap,type ClientMindMapNode,type PositionedMindMapNode} from './client-mind-maps';
import './client-mind-maps.css';
import './client-mind-maps-freeform.css';
import {FullscreenButton,useFullscreenPanel} from './FullscreenPanel';

type Props={clientId:string;maps:ClientMindMap[];onChange:(maps:ClientMindMap[])=>void};
type MapDraft={id?:string;title:string;description:string;rootText:string;createdAt?:string};
type QuickDraft={x:number;y:number;parentId:string|null;text:string};
type DragState={nodeId:string;x:number;y:number;offsetX:number;offsetY:number};
type Direction='top'|'right'|'bottom'|'left';
const colors=['#5b36f2','#2563eb','#059669','#d97706','#dc2626','#db2777','#0891b2','#475569'],canvasWidth=1080,canvasHeight=620;
const directionOffset:Record<Direction,{x:number;y:number}>={top:{x:0,y:-130},right:{x:210,y:0},bottom:{x:0,y:130},left:{x:-210,y:0}};

export default function ClientMindMapsPanel({clientId,maps,onChange}:Props){
 const mapFullscreen=useFullscreenPanel<HTMLDivElement>();
 const [selectedId,setSelectedId]=useState(maps[0]?.id||''),[selectedNodeId,setSelectedNodeId]=useState(''),[nodeText,setNodeText]=useState(''),[branchText,setBranchText]=useState(''),[draft,setDraft]=useState<MapDraft|null>(null),[quickDraft,setQuickDraft]=useState<QuickDraft|null>(null),[dragging,setDragging]=useState<DragState|null>(null);
 const selected=maps.find(map=>map.id===selectedId)||maps[0],root=selected?mindMapRoot(selected.nodes):undefined,selectedNode=selected?.nodes.find(node=>node.id===selectedNodeId),automaticPositions=useMemo(()=>layoutMindMapNodes(selected?.nodes||[],canvasWidth,canvasHeight),[selected]),positioned=automaticPositions.map(node=>node.id===dragging?.nodeId?{...node,x:dragging.x,y:dragging.y}:node);
 useEffect(()=>{if(!maps.length){setSelectedId('');setSelectedNodeId('');return}if(!maps.some(map=>map.id===selectedId))setSelectedId(maps[0].id)},[maps,selectedId]);
 useEffect(()=>{const node=selected?.nodes.find(item=>item.id===selectedNodeId)||root;if(node){setSelectedNodeId(node.id);setNodeText(node.text)}},[selected?.id,selectedNodeId,selectedNode?.text,root?.id]);

 const updateMap=(map:ClientMindMap)=>onChange(maps.map(item=>item.id===map.id?map:item));
 const openNew=()=>setDraft({title:'',description:'',rootText:''});
 const openEdit=()=>selected&&setDraft({id:selected.id,title:selected.title,description:selected.description,rootText:root?.text||selected.title,createdAt:selected.createdAt});
 const saveMap=(event:React.FormEvent)=>{event.preventDefault();if(!draft)return;const now=new Date().toISOString(),title=draft.title.trim(),rootText=draft.rootText.trim()||title;if(!title||!rootText)return;if(draft.id&&selected){const rootId=root?.id,updated={...selected,title,description:draft.description.trim(),updatedAt:now,nodes:selected.nodes.map(node=>node.id===rootId?{...node,text:rootText}:node)};updateMap(updated);setSelectedId(updated.id)}else{const map:ClientMindMap={id:crypto.randomUUID(),clientId,title,description:draft.description.trim(),nodes:[{id:crypto.randomUUID(),parentId:null,text:rootText,color:colors[0],x:canvasWidth/2,y:canvasHeight/2}],createdAt:now,updatedAt:now};onChange([map,...maps]);setSelectedId(map.id);setSelectedNodeId(map.nodes[0].id)}setDraft(null)};
 const selectNode=(node:ClientMindMapNode)=>{setSelectedNodeId(node.id);setNodeText(node.text)};
 const saveNode=()=>{if(!selected||!selectedNode||!nodeText.trim())return;updateMap({...selected,updatedAt:new Date().toISOString(),nodes:selected.nodes.map(node=>node.id===selectedNode.id?{...node,text:nodeText.trim()}:node)})};
 const setNodeColor=(color:string)=>{if(!selected||!selectedNode)return;updateMap({...selected,updatedAt:new Date().toISOString(),nodes:selected.nodes.map(node=>node.id===selectedNode.id?{...node,color}:node)})};
 const startQuickDraft=(x:number,y:number,parentId:string|null)=>{const position=clampMindMapPosition(x,y,canvasWidth,canvasHeight);setQuickDraft({...position,parentId,text:''})};
 const saveQuickDraft=(event:React.FormEvent)=>{event.preventDefault();if(!selected||!quickDraft?.text.trim())return;const node:ClientMindMapNode={id:crypto.randomUUID(),parentId:quickDraft.parentId,text:quickDraft.text.trim(),color:colors[selected.nodes.length%colors.length],x:quickDraft.x,y:quickDraft.y};updateMap({...selected,nodes:[...selected.nodes,node],updatedAt:new Date().toISOString()});setSelectedNodeId(node.id);setNodeText(node.text);setQuickDraft(null)};
 const createBranchFromHandle=(node:PositionedMindMapNode,direction:Direction)=>{const offset=directionOffset[direction];selectNode(node);startQuickDraft(node.x+offset.x,node.y+offset.y,node.id)};
 const addBranch=(event:React.FormEvent)=>{event.preventDefault();if(!selected||!selectedNode||!branchText.trim())return;const current=positioned.find(node=>node.id===selectedNode.id),siblings=selected.nodes.filter(node=>node.parentId===selectedNode.id).length,position=clampMindMapPosition((current?.x||canvasWidth/2)+210,(current?.y||canvasHeight/2)+(siblings%5-2)*70,canvasWidth,canvasHeight),node:ClientMindMapNode={id:crypto.randomUUID(),parentId:selectedNode.id,text:branchText.trim(),color:colors[selected.nodes.length%colors.length],...position};updateMap({...selected,updatedAt:new Date().toISOString(),nodes:[...selected.nodes,node]});setBranchText('');setSelectedNodeId(node.id);setNodeText(node.text)};
 const deleteBranch=()=>{if(!selected||!selectedNode||selectedNode.id===root?.id)return;if(confirm(`Excluir “${selectedNode.text}” e suas ramificações?`)){const nodes=removeMindMapBranch(selected.nodes,selectedNode.id);updateMap({...selected,nodes,updatedAt:new Date().toISOString()});setSelectedNodeId(root?.id||'')}};
 const deleteMap=()=>{if(selected&&confirm(`Excluir o mapa mental “${selected.title}”?`)){const next=maps.filter(map=>map.id!==selected.id);onChange(next);setSelectedId(next[0]?.id||'')}};
 const startDrag=(event:React.PointerEvent<HTMLDivElement>,node:PositionedMindMapNode)=>{if((event.target as Element).closest('.mindMapHandle'))return;const rect=event.currentTarget.parentElement!.getBoundingClientRect();event.currentTarget.setPointerCapture(event.pointerId);selectNode(node);setDragging({nodeId:node.id,x:node.x,y:node.y,offsetX:event.clientX-rect.left-node.x,offsetY:event.clientY-rect.top-node.y})};
 const moveDrag=(event:React.PointerEvent<HTMLDivElement>)=>{if(!dragging)return;const rect=event.currentTarget.parentElement!.getBoundingClientRect(),position=clampMindMapPosition(event.clientX-rect.left-dragging.offsetX,event.clientY-rect.top-dragging.offsetY,canvasWidth,canvasHeight);setDragging({...dragging,...position})};
 const endDrag=()=>{if(!dragging||!selected)return;updateMap({...selected,updatedAt:new Date().toISOString(),nodes:selected.nodes.map(node=>node.id===dragging.nodeId?{...node,x:dragging.x,y:dragging.y}:node)});setDragging(null)};
 const createFreeTopic=(event:React.MouseEvent<HTMLDivElement>)=>{if((event.target as Element).closest('.mindMapNode,.mindMapQuickEditor'))return;const rect=event.currentTarget.getBoundingClientRect();startQuickDraft(event.clientX-rect.left,event.clientY-rect.top,null)};

 return <section className="mindMapsWorkspace">
  <div className="mindMapsHead"><div><span><BrainCircuit/></span><div><h3>Mapas mentais</h3><p>Crie tópicos livremente, conecte ideias e arraste tudo pela grade.</p></div></div><button type="button" className="btn" onClick={openNew}><Plus/> Novo mapa</button></div>
  {!maps.length?<div className="card mindMapsEmpty"><BrainCircuit/><h3>Nenhum mapa mental criado</h3><p>Crie um mapa para estruturar campanhas, estratégias, públicos, conteúdos ou qualquer fluxo de ideias.</p><button type="button" className="btn secondary" onClick={openNew}><Plus/> Criar primeiro mapa</button></div>:<div className="mindMapsLayout">
   <aside className="card mindMapList"><header><b>Seus mapas</b><span>{maps.length}</span></header>{maps.map(map=><button type="button" className={map.id===selected?.id?'active':''} key={map.id} onClick={()=>{setSelectedId(map.id);setSelectedNodeId('');setQuickDraft(null)}}><span><Network/></span><div><b>{map.title}</b><small>{map.nodes.length} {map.nodes.length===1?'tópico':'tópicos'}</small></div></button>)}</aside>
   {selected&&<div ref={mapFullscreen.ref} className={`mindMapMain fullscreenSurface${mapFullscreen.active?' fullscreenSurfaceActive':''}`}><div className="card mindMapToolbar"><div><h4>{selected.title}</h4><p>{selected.description||'Mapa mental do cliente'}</p></div><div><button type="button" className="mindMapNewTopic" onClick={()=>startQuickDraft(canvasWidth/2+80,canvasHeight/2+80,null)}><Plus/> Tópico livre</button><FullscreenButton active={mapFullscreen.active} onClick={mapFullscreen.toggle} label="mapa mental"/><button type="button" onClick={openEdit}><Pencil/> Editar mapa</button><button type="button" className="danger" onClick={deleteMap}><Trash2/> Excluir</button></div></div>
    <div className="card mindMapCanvasScroll"><div className="mindMapCanvas" onDoubleClick={createFreeTopic}><div className="mindMapCanvasHint"><MousePointer2/> Arraste os tópicos · use os botões + para criar ramos · duplo clique para criar livremente</div><svg viewBox={`0 0 ${canvasWidth} ${canvasHeight}`} aria-hidden="true">{positioned.filter(node=>node.parentId).map(node=>{const parent=positioned.find(item=>item.id===node.parentId);if(!parent)return null;const middle=(parent.x+node.x)/2;return <path key={node.id} d={`M ${parent.x} ${parent.y} C ${middle} ${parent.y}, ${middle} ${node.y}, ${node.x} ${node.y}`}/>} )}</svg>{positioned.map(node=><div role="button" tabIndex={0} aria-label={`Tópico ${node.text}`} key={node.id} className={`mindMapNode${node.id===selectedNode?.id?' selected':''}${node.id===root?.id?' root':''}${node.id===dragging?.nodeId?' dragging':''}`} style={{left:node.x,top:node.y,borderColor:node.color,'--node-color':node.color} as React.CSSProperties} onClick={()=>selectNode(node)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')selectNode(node)}} onPointerDown={event=>startDrag(event,node)} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={()=>setDragging(null)}><span>{node.id===root?.id?<BrainCircuit/>:<GitBranch/>}</span><b>{node.text}</b>{(['top','right','bottom','left'] as Direction[]).map(direction=><button type="button" className={`mindMapHandle ${direction}`} aria-label={`Criar ramo ${direction}`} title="Criar ramo" key={direction} onPointerDown={event=>event.stopPropagation()} onClick={event=>{event.stopPropagation();createBranchFromHandle(node,direction)}}><Plus/></button>)}</div>)}{quickDraft&&<form className="mindMapQuickEditor" style={{left:quickDraft.x,top:quickDraft.y}} onSubmit={saveQuickDraft}><input autoFocus value={quickDraft.text} onChange={event=>setQuickDraft(current=>current?{...current,text:event.target.value}:current)} onKeyDown={event=>{if(event.key==='Escape')setQuickDraft(null)}} placeholder={quickDraft.parentId?'Nome do novo ramo':'Nome do tópico livre'}/><button type="submit" aria-label="Criar tópico" disabled={!quickDraft.text.trim()}><Check/></button><button type="button" aria-label="Cancelar tópico" onClick={()=>setQuickDraft(null)}><X/></button></form>}</div></div>
    {selectedNode&&<section className="card mindMapInspector"><div className="mindMapNodeEditor"><div><small>{selectedNode.id===root?.id?'TÓPICO CENTRAL':selectedNode.parentId?'RAMIFICAÇÃO SELECIONADA':'TÓPICO LIVRE'}</small><b>Editar tópico</b></div><input value={nodeText} onChange={event=>setNodeText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')saveNode()}}/><button type="button" onClick={saveNode} disabled={!nodeText.trim()}><Save/> Salvar</button></div><div className="mindMapColors"><span>Cor</span>{colors.map(color=><button type="button" aria-label={`Usar cor ${color}`} className={selectedNode.color===color?'active':''} key={color} style={{background:color}} onClick={()=>setNodeColor(color)}/>)}</div><form className="mindMapAddBranch" onSubmit={addBranch}><label><span>Novo ramo conectado a <b>{selectedNode.text}</b></span><input value={branchText} onChange={event=>setBranchText(event.target.value)} placeholder="Digite uma nova ideia..."/></label><button className="btn" disabled={!branchText.trim()}><Plus/> Adicionar</button></form>{selectedNode.id!==root?.id&&<button type="button" className="mindMapDeleteBranch" onClick={deleteBranch}><Trash2/> Excluir este tópico</button>}</section>}
   </div>}
  </div>}
  {draft&&<div className="overlay"><div className="modal mindMapModal" role="dialog" aria-modal="true" aria-labelledby="mind-map-dialog-title"><div className="modalHead"><div><small>MAPA MENTAL</small><h2 id="mind-map-dialog-title">{draft.id?'Editar mapa mental':'Novo mapa mental'}</h2><p>Comece pelo assunto principal e depois adicione as ramificações livremente.</p></div><button type="button" className="iconBtn" aria-label="Fechar" onClick={()=>setDraft(null)}><X/></button></div><form className="form" onSubmit={saveMap}><label className="full">Nome do mapa<input autoFocus required value={draft.title} onChange={event=>setDraft(current=>current?{...current,title:event.target.value}:current)} placeholder="Ex.: Estratégia de lançamento"/></label><label className="full">Descrição<textarea value={draft.description} onChange={event=>setDraft(current=>current?{...current,description:event.target.value}:current)} placeholder="Objetivo ou contexto deste mapa"/></label><label className="full">Tópico central<input required value={draft.rootText} onChange={event=>setDraft(current=>current?{...current,rootText:event.target.value}:current)} placeholder="Ex.: Lançamento do produto"/></label><div className="formActions full"><button type="button" className="btn secondary" onClick={()=>setDraft(null)}>Cancelar</button><button className="btn" disabled={!draft.title.trim()||!draft.rootText.trim()}>{draft.id?'Salvar alterações':'Criar mapa'}</button></div></form></div></div>}
 </section>;
}
