import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,BriefcaseBusiness,CalendarDays,CheckCircle2,ChevronRight,CircleDollarSign,ClipboardCheck,Clock3,FileText,FolderOpen,History,Mail,MapPin,Phone,Plus,ReceiptText,UsersRound} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import {store} from './storage';
import type {Client,GenericItem,Project,Task,TeamMember} from './types';
import type {AgencyService} from './ServicesManager';
import {linkedServices} from './service-links';
import ClientTaskModal from './ClientTaskModal';

type HubTab='overview'|'operation'|'finance'|'content'|'history';
type FinancialEntry={id:string;clientId:string;serviceId?:string;description:string;kind:'recurring'|'variable'|'one_off';value:number;dueDate:string;status:'pending'|'received';receivedAt?:string;notes?:string;createdAt?:string;updatedAt?:string};
type StepState={completed:boolean;completedAt:string;responsibleId:string;notes:string};
type OnboardingRecord={clientId:string;steps:Record<string,StepState>};
type HistoryItem={id:string;type:string;title:string;detail:string;date:string};
const money=(value=0)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const initials=(name:string)=>name.split(' ').slice(0,2).map(part=>part[0]).join('').toUpperCase();
const formatDate=(date?:string)=>date?new Date(date.length===10?`${date}T12:00:00`:date).toLocaleDateString('pt-BR'):'—';
const onboardingLabels:Record<string,string>={contract:'Contrato assinado',payment:'Pagamento inicial',accesses:'Acessos recebidos',briefing:'Reunião de briefing',strategy:'Estratégia aprovada',project:'Projeto iniciado'};

export default function ClientHubPage(){
 const {clientId}=useParams(),navigate=useNavigate();
 const [clients,setClients]=useState<Client[]>(()=>store.get('clients',[])),[services,setServices]=useState<AgencyService[]>(()=>store.get('services',[])),[projects,setProjects]=useState<Project[]>(()=>store.get('projects',[])),[tasks,setTasks]=useState<Task[]>(()=>store.get('tasks',[])),[team,setTeam]=useState<TeamMember[]>(()=>store.get('team',[])),[entries,setEntries]=useState<FinancialEntry[]>(()=>store.get('financial_entries',[])),[documents,setDocuments]=useState<GenericItem[]>(()=>store.get('documents',[])),[reports,setReports]=useState<GenericItem[]>(()=>store.get('reports',[])),[onboarding,setOnboarding]=useState<OnboardingRecord[]>(()=>store.get('onboarding',[]));
 const [tab,setTab]=useState<HubTab>('overview'),[taskModal,setTaskModal]=useState(false);
 useEffect(()=>{const update=()=>{setClients(store.get('clients',[]));setServices(store.get('services',[]));setProjects(store.get('projects',[]));setTasks(store.get('tasks',[]));setTeam(store.get('team',[]));setEntries(store.get('financial_entries',[]));setDocuments(store.get('documents',[]));setReports(store.get('reports',[]));setOnboarding(store.get('onboarding',[]))};window.addEventListener('roas-change',update);return()=>window.removeEventListener('roas-change',update)},[]);
 const client=clients.find(item=>item.id===clientId);
 if(!client)return <main className="clientHubMissing"><UsersRound/><h2>Cliente não encontrado</h2><p>O cadastro pode ter sido removido ou não está mais disponível.</p><button className="btn" onClick={()=>navigate('/clients')}><ArrowLeft/> Voltar para clientes</button></main>;
 const clientServices=linkedServices(client,services),clientProjects=projects.filter(project=>project.clientId===client.id),clientTasks=tasks.filter(task=>task.clientId===client.id),clientEntries=entries.filter(entry=>entry.clientId===client.id),clientDocuments=documents.filter(item=>item.clientId===client.id),clientReports=reports.filter(item=>item.clientId===client.id);
 const responsible=team.filter(member=>(client.responsibleIds||[client.managerId]).includes(member.id)||member.clientIds?.includes(client.id)),openTasks=clientTasks.filter(task=>task.status!=='completed'),activeProjects=clientProjects.filter(project=>project.status==='active');
 const received=clientEntries.filter(entry=>entry.status==='received').reduce((sum,entry)=>sum+entry.value,0),pending=clientEntries.filter(entry=>entry.status!=='received').reduce((sum,entry)=>sum+entry.value,0);
 const onboardingRecord=onboarding.find(record=>record.clientId===client.id),onboardingSteps=Object.entries(onboardingLabels).map(([id,label])=>({id,label,state:onboardingRecord?.steps?.[id]})),onboardingProgress=Math.round(onboardingSteps.filter(step=>step.state?.completed).length/onboardingSteps.length*100);
 const history:HistoryItem[]=[
  {id:`client-created-${client.id}`,type:'client',title:'Cliente cadastrado',detail:'Cadastro criado no sistema',date:client.createdAt},
  {id:`client-updated-${client.id}`,type:'client',title:'Cadastro atualizado',detail:'Informações cadastrais revisadas',date:client.updatedAt},
  ...clientProjects.map(project=>({id:`project-${project.id}`,type:'project',title:`Projeto ${project.status==='completed'?'concluído':'atualizado'}`,detail:project.name,date:project.updatedAt})),
  ...clientTasks.filter(task=>task.status==='completed').map(task=>({id:`task-${task.id}`,type:'task',title:'Tarefa concluída',detail:task.title,date:task.updatedAt})),
  ...clientEntries.filter(entry=>entry.status==='received').map(entry=>({id:`finance-${entry.id}`,type:'finance',title:'Pagamento recebido',detail:`${entry.description} · ${money(entry.value)}`,date:entry.receivedAt||entry.updatedAt||entry.dueDate})),
  ...clientDocuments.map(item=>({id:`document-${item.id}`,type:'document',title:'Documento adicionado',detail:item.name,date:item.updatedAt})),
  ...clientReports.map(item=>({id:`report-${item.id}`,type:'report',title:'Relatório registrado',detail:item.name,date:item.updatedAt})),
  ...onboardingSteps.filter(step=>step.state?.completedAt).map(step=>({id:`onboarding-${step.id}`,type:'onboarding',title:'Etapa de onboarding concluída',detail:step.label,date:step.state!.completedAt})),
 ].filter(item=>item.date).sort((a,b)=>b.date.localeCompare(a.date));
 return <main className="clientHub"><div className="hubBack"><button onClick={()=>navigate('/clients')}><ArrowLeft/> Clientes</button><ChevronRight/><span>{client.companyName}</span></div><section className="card hubHero"><div className="hubIdentity"><span className="avatar" style={{background:client.color}}>{initials(client.companyName)}</span><div><small>CENTRAL DO CLIENTE</small><h2>{client.companyName}</h2><p>{client.segment||'Segmento não informado'} · {client.city||'Cidade não informada'}</p><div><span className={`badge ${client.status==='active'?'green':client.status==='prospect'?'orange':'red'}`}>{client.status==='active'?'Ativo':client.status==='prospect'?'Prospect':'Inativo'}</span>{clientServices.slice(0,3).map(service=><span className="tag" key={service.id}>{service.name}</span>)}</div></div></div><div className="hubHeroActions"><button className="btn secondary" onClick={()=>navigate('/clients')}>Editar cadastro</button><button className="btn" onClick={()=>setTaskModal(true)}><Plus/> Nova tarefa</button></div></section><div className="hubStats"><HubStat icon={<CircleDollarSign/>} label="Receita mensal" value={money(client.monthlyRevenue)} note={`${clientServices.length} serviços contratados`}/><HubStat icon={<BriefcaseBusiness/>} label="Projetos ativos" value={String(activeProjects.length)} note={`${clientProjects.length} projetos no total`} tone="blue"/><HubStat icon={<ClipboardCheck/>} label="Tarefas abertas" value={String(openTasks.length)} note={`${clientTasks.filter(task=>task.status==='completed').length} concluídas`} tone="orange"/><HubStat icon={<ReceiptText/>} label="Valores recebidos" value={money(received)} note={`${money(pending)} pendentes`} tone="green"/><HubStat icon={<CheckCircle2/>} label="Onboarding" value={`${onboardingProgress}%`} note={onboardingProgress===100?'Concluído':'Em andamento'} tone="purple"/></div><div className="hubTabs">{([['overview','Visão geral'],['operation','Operação'],['finance','Financeiro'],['content','Arquivos e relatórios'],['history','Histórico']] as [HubTab,string][]).map(([value,label])=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{label}</button>)}</div>{tab==='overview'&&<Overview client={client} services={clientServices} responsible={responsible} onboardingSteps={onboardingSteps} onboardingProgress={onboardingProgress}/>} {tab==='operation'&&<Operation projects={clientProjects} tasks={clientTasks} team={responsible} clients={clients}/>} {tab==='finance'&&<Finance entries={clientEntries} services={services} received={received} pending={pending} monthlyRevenue={client.monthlyRevenue}/>} {tab==='content'&&<Content documents={clientDocuments} reports={clientReports}/>} {tab==='history'&&<HistoryPanel items={history}/>} {taskModal&&<ClientTaskModal client={client} onClose={()=>setTaskModal(false)}/>}</main>
}

function Overview({client,services,responsible,onboardingSteps,onboardingProgress}:{client:Client;services:AgencyService[];responsible:TeamMember[];onboardingSteps:{id:string;label:string;state?:StepState}[];onboardingProgress:number}){return <div className="hubOverview"><section className="card hubSection"><Title title="Dados cadastrais" subtitle="Informações principais do cliente"/><div className="profileFields"><Field icon={<Mail/>} label="E-mail" value={client.email}/><Field icon={<Phone/>} label="Telefone" value={client.phone}/><Field icon={<MapPin/>} label="Localização" value={client.city}/><Field icon={<CalendarDays/>} label="Início do contrato" value={formatDate(client.startDate)}/><Field icon={<UsersRound/>} label="Contato principal" value={client.contactName}/><Field icon={<BriefcaseBusiness/>} label="Segmento" value={client.segment}/></div>{client.notes&&<div className="clientNotes"><b>Observações</b><p>{client.notes}</p></div>}</section><section className="card hubSection"><Title title="Serviços contratados" subtitle="Catálogo vinculado por identificador" action={<a href="/settings">Gerenciar <ArrowRight/></a>}/><div className="hubServices">{services.map(service=><article key={service.id}><span>✦</span><div><b>{service.name}</b><small>{service.description||'Sem descrição'}</small></div><strong>{service.pricingType==='variable'?'Valor variável':`${money(service.price)}/mês`}</strong></article>)}{!services.length&&<Empty icon={<BriefcaseBusiness/>} text="Nenhum serviço vinculado."/>}</div></section><section className="card hubSection"><Title title="Equipe responsável" subtitle="Pessoas que atendem este cliente" action={<a href="/team">Ver equipe <ArrowRight/></a>}/><div className="hubTeam">{responsible.map(member=><article key={member.id}><span className="avatar" style={{background:member.color}}>{initials(member.name)}</span><div><b>{member.name}</b><small>{member.roles?.join(', ')||member.role}</small></div><span className="badge green">Ativo</span></article>)}{!responsible.length&&<Empty icon={<UsersRound/>} text="Nenhum responsável definido."/>}</div></section><section className="card hubSection onboardingSummary"><Title title="Onboarding" subtitle={`${onboardingProgress}% concluído`} action={<a href="/onboarding">Abrir onboarding <ArrowRight/></a>}/><div className="hubProgress"><i><em style={{width:`${onboardingProgress}%`}}/></i><strong>{onboardingProgress}%</strong></div>{onboardingSteps.map(step=><div className={`hubOnboardingStep ${step.state?.completed?'done':''}`} key={step.id}><span>{step.state?.completed?<CheckCircle2/>:<Clock3/>}</span><div><b>{step.label}</b><small>{step.state?.completedAt?`Concluído em ${formatDate(step.state.completedAt)}`:'Aguardando conclusão'}</small></div></div>)}</section></div>}
function Operation({projects,tasks,team,clients}:{projects:Project[];tasks:Task[];team:TeamMember[];clients:Client[]}){return <div className="hubOperation"><section className="card hubSection"><Title title="Projetos" subtitle={`${projects.length} projetos vinculados`} action={<a href="/projects">Ver projetos <ArrowRight/></a>}/><div className="hubProjectList">{projects.map(project=><article key={project.id}><span className="projectIcon"><BriefcaseBusiness/></span><div><b>{project.name}</b><small>{project.description}</small><i><em style={{width:`${project.progress}%`}}/></i></div><strong>{project.progress}%</strong><span className={`hubStatus ${project.status}`}>{project.status==='active'?'Ativo':project.status==='completed'?'Concluído':project.status==='paused'?'Pausado':'Planejamento'}</span></article>)}{!projects.length&&<Empty icon={<BriefcaseBusiness/>} text="Nenhum projeto vinculado."/>}</div></section><section className="card hubSection"><Title title="Tarefas" subtitle={`${tasks.filter(task=>task.status!=='completed').length} tarefas abertas`} action={<a href="/tasks">Ver tarefas <ArrowRight/></a>}/><div className="hubTaskList">{tasks.slice(0,10).map(task=><article key={task.id}><span className={`taskState ${task.status}`}>{task.status==='completed'?<CheckCircle2/>:<ClipboardCheck/>}</span><div><b>{task.title}</b><small>{task.description}</small></div><span className={`taskPriority ${task.priority}`}>{task.priority==='urgent'?'Urgente':task.priority==='high'?'Alta':task.priority==='medium'?'Média':'Baixa'}</span><time>{formatDate(task.dueDate)}</time></article>)}{!tasks.length&&<Empty icon={<ClipboardCheck/>} text="Nenhuma tarefa vinculada."/>}</div></section><section className="card hubSection operationTeam"><Title title="Equipe da conta" subtitle="Responsáveis envolvidos na operação"/>{team.map(member=><article key={member.id}><span className="avatar" style={{background:member.color}}>{initials(member.name)}</span><b>{member.name}</b><small>{member.roles?.join(', ')||member.role}</small></article>)}</section></div>}
function Finance({entries,services,received,pending,monthlyRevenue}:{entries:FinancialEntry[];services:AgencyService[];received:number;pending:number;monthlyRevenue:number}){return <div className="hubFinance"><section className="financeHubStats"><article><small>Receita recorrente</small><strong>{money(monthlyRevenue)}</strong><span>por mês</span></article><article><small>Total recebido</small><strong>{money(received)}</strong><span>histórico registrado</span></article><article><small>Pagamentos pendentes</small><strong>{money(pending)}</strong><span>{entries.filter(entry=>entry.status!=='received').length} cobranças</span></article></section><section className="card hubSection"><Title title="Movimentações financeiras" subtitle={`${entries.length} lançamentos deste cliente`} action={<a href="/finance">Abrir financeiro <ArrowRight/></a>}/><div className="tableWrap"><table><thead><tr><th>Descrição</th><th>Serviço</th><th>Vencimento</th><th>Status</th><th>Valor</th></tr></thead><tbody>{[...entries].sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).map(entry=><tr key={entry.id}><td><b>{entry.description}</b></td><td>{services.find(service=>service.id===entry.serviceId)?.name||'—'}</td><td>{formatDate(entry.dueDate)}</td><td><span className={`hubPayment ${entry.status}`}>{entry.status==='received'?'Recebido':'Pendente'}</span></td><td><strong>{money(entry.value)}</strong></td></tr>)}</tbody></table>{!entries.length&&<Empty icon={<ReceiptText/>} text="Nenhuma movimentação financeira."/>}</div></section></div>}
function Content({documents,reports}:{documents:GenericItem[];reports:GenericItem[]}){return <div className="hubContent"><section className="card hubSection"><Title title="Documentos do cliente" subtitle={`${documents.length} arquivos vinculados`}/><div className="hubFiles">{documents.map(item=><article key={item.id}><span><FileText/></span><div><b>{item.name}</b><small>{item.description||item.category}</small></div><time>{formatDate(item.updatedAt)}</time></article>)}{!documents.length&&<Empty icon={<FolderOpen/>} text="Nenhum documento vinculado."/>}</div></section><section className="card hubSection"><Title title="Relatórios" subtitle={`${reports.length} relatórios do cliente`} action={<a href="/reports">Abrir relatórios <ArrowRight/></a>}/><div className="hubFiles reports">{reports.map(item=><article key={item.id}><span><ReceiptText/></span><div><b>{item.name}</b><small>{item.status} · {item.description}</small></div><time>{formatDate(item.updatedAt)}</time></article>)}{!reports.length&&<Empty icon={<ReceiptText/>} text="Nenhum relatório vinculado."/>}</div></section></div>}
function HistoryPanel({items}:{items:HistoryItem[]}){return <section className="card hubSection hubHistory"><Title title="Histórico do cliente" subtitle="Linha do tempo unificada de todas as áreas"/>{items.map(item=><article key={item.id}><span className={`historyIcon ${item.type}`}>{item.type==='finance'?<CircleDollarSign/>:item.type==='task'?<CheckCircle2/>:item.type==='document'||item.type==='report'?<FileText/>:item.type==='project'?<BriefcaseBusiness/>:item.type==='onboarding'?<ClipboardCheck/>:<History/>}</span><div><b>{item.title}</b><small>{item.detail}</small></div><time>{formatDate(item.date)}</time></article>)}{!items.length&&<Empty icon={<History/>} text="Nenhuma atividade registrada."/>}</section>}
function HubStat({icon,label,value,note,tone='' }:{icon:React.ReactNode;label:string;value:string;note:string;tone?:string}){return <article><span className={`hubStatIcon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>}
function Title({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="hubTitle"><div><h3>{title}</h3><p>{subtitle}</p></div>{action}</div>}
function Field({icon,label,value}:{icon:React.ReactNode;label:string;value?:string}){return <div><span>{icon}</span><p><small>{label}</small><b>{value||'Não informado'}</b></p></div>}
function Empty({icon,text}:{icon:React.ReactNode;text:string}){return <div className="hubEmpty">{icon}<span>{text}</span></div>}
