import CompactFilters from './CompactFilters';
import {useEffect,useMemo,useState} from 'react';
import {Activity,DollarSign,Download,Plus,Search,Users,UserRoundCheck,X} from 'lucide-react';
import {store} from './storage';
import type {Client,GenericItem,Project,Task,TeamMember} from './types';
import type {AgencyService} from './ServicesManager';
import {linkedServices} from './service-links';
import {ClientForm} from './ClientForm';
import ClientTaskModal from './ClientTaskModal';
import {usePersistentState} from './persistent-ui';
import {clientHealthLabel,evaluateClientHealth,type ClientHealth,type ClientHealthLevel,type HealthOnboarding,type HealthPayment} from './client-health';
import {canAccessPath} from './app/access-control';
import './client-health.css';
const money=(n=0)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const initials=(name:string)=>name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();

export default function ClientsPageEnhanced(){
 const [clients,setClients]=useState<Client[]>(()=>store.get('clients',[])),[projects,setProjects]=useState<Project[]>(()=>store.get('projects',[])),[tasks,setTasks]=useState<Task[]>(()=>store.get('tasks',[])),[payments,setPayments]=useState<HealthPayment[]>(()=>store.get('financial_entries',[])),[reports,setReports]=useState<GenericItem[]>(()=>store.get('reports',[])),[onboarding,setOnboarding]=useState<HealthOnboarding[]>(()=>store.get('onboarding',[])),[services,setServices]=useState<AgencyService[]>(()=>store.get('services',[])),[team,setTeam]=useState<TeamMember[]>(()=>store.get('team',[]));
 const [query,setQuery]=usePersistentState('roas_filter_clients_query',''),[tab,setTab]=usePersistentState('roas_filter_clients_status','active'),[healthFilter,setHealthFilter]=usePersistentState<ClientHealthLevel|'all'>('roas_filter_clients_health','all'),[selected,setSelected]=useState<Client|null>(null),[creating,setCreating]=useState(false),[taskClient,setTaskClient]=useState<Client|null>(null);
 useEffect(()=>{const update=()=>{const next=store.get<Client[]>('clients',[]);setClients(next);setProjects(store.get('projects',[]));setTasks(store.get('tasks',[]));setPayments(store.get('financial_entries',[]));setReports(store.get('reports',[]));setOnboarding(store.get('onboarding',[]));setServices(store.get('services',[]));setTeam(store.get('team',[]));setSelected(current=>current?next.find(client=>client.id===current.id)||null:current)};window.addEventListener('roas-change',update);return()=>window.removeEventListener('roas-change',update)},[]);
 const save=(next:Client[])=>{setClients(next);store.set('clients',next)};
 const serviceNames=(client:Client)=>linkedServices(client,services).map(service=>service.name);
 const access=store.access(),canViewFinance=canAccessPath(access?.member||undefined,'/finance',access?.accessAreas),canViewReports=canAccessPath(access?.member||undefined,'/marketing/reports',access?.accessAreas);
 const healthById=useMemo(()=>new Map(clients.map(client=>[client.id,evaluateClientHealth(client,{tasks,projects,payments:canViewFinance?payments:[],reports:canViewReports?reports:[],onboarding,assignedMemberCount:team.filter(member=>member.status==='active'&&((client.responsibleIds||[client.managerId]).includes(member.id)||member.clientIds?.includes(client.id))).length,serviceCount:linkedServices(client,services).length})])),[clients,tasks,projects,payments,reports,onboarding,team,services,canViewFinance,canViewReports]);
 const activeHealth=clients.filter(client=>client.status==='active').map(client=>healthById.get(client.id)!);
 const atRisk=activeHealth.filter(item=>item.level==='critical'||item.level==='attention');
 const atRiskRevenue=clients.filter(client=>atRisk.some(item=>item.clientId===client.id)).reduce((sum,client)=>sum+client.monthlyRevenue,0);
 const filtered=useMemo(()=>clients.filter(client=>(tab==='all'||client.status===tab)&&(healthFilter==='all'||healthById.get(client.id)?.level===healthFilter)&&`${client.companyName} ${client.contactName} ${client.cnpj||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(healthById.get(a.id)?.score??101)-(healthById.get(b.id)?.score??101)||a.companyName.localeCompare(b.companyName,'pt-BR')),[clients,tab,healthFilter,healthById,query]);
 const revenue=clients.filter(client=>client.status==='active').reduce((sum,client)=>sum+client.monthlyRevenue,0);
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),responsibleIds=form.getAll('responsibleIds').map(String),id=crypto.randomUUID();const client:Client={id,sourceLeadId:undefined,companyName:String(form.get('companyName')),contactName:String(form.get('contactName')),email:String(form.get('email')),phone:String(form.get('phone')),instagram:String(form.get('instagram')),segment:String(form.get('segment')),city:String(form.get('city')),cnpj:String(form.get('cnpj')).trim(),paymentDay:Number(form.get('paymentDay')||0)||undefined,status:String(form.get('status')) as Client['status'],managerId:responsibleIds[0]||'',responsibleIds,monthlyRevenue:Number(form.get('monthlyRevenue')||0),serviceIds:form.getAll('serviceIds').map(String),startDate:String(form.get('startDate')),notes:String(form.get('notes')),color:'#5b36f2',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};save([client,...clients]);const nextTeam=team.map(member=>({...member,clientIds:responsibleIds.includes(member.id)?Array.from(new Set([...(member.clientIds||[]),id])):(member.clientIds||[]).filter(clientId=>clientId!==id)}));setTeam(nextTeam);store.set('team',nextTeam);setCreating(false)};
 const exportCsv=()=>{const text='Empresa,CNPJ,Contato,Email,Dia do pagamento,Responsáveis,Status,Receita,Serviços\n'+clients.map(client=>[client.companyName,client.cnpj||'',client.contactName,client.email,client.paymentDay||'',team.filter(member=>(client.responsibleIds||[client.managerId]).includes(member.id)).map(member=>member.name).join(' | '),client.status,client.monthlyRevenue,serviceNames(client).join(' | ')].map(value=>`"${value}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));link.download='clientes-roas.csv';link.click()};
 return <main>
  <div className="clientsTop"><div className="clientStats"><Stat icon={<Users/>} label="Total de clientes" value={String(clients.length)}/><Stat icon={<UserRoundCheck/>} label="Clientes ativos" value={String(activeHealth.length)} tone="blue"/><Stat icon={<DollarSign/>} label="Receita mensal" value={money(revenue)} tone="green"/><Stat icon={<DollarSign/>} label="Ticket médio" value={money(revenue/Math.max(1,activeHealth.length))} tone="orange"/></div><div className="clientTopActions"><button className="btn" onClick={()=>setCreating(true)}><Plus/> Novo cliente</button><button className="btn secondary" onClick={exportCsv}><Download/> Exportar</button></div></div>
  <section className="portfolioOverview" aria-label="Saúde da carteira"><div className="portfolioOverviewHeading"><Activity/><span><b>Saúde da carteira</b><small>Clientes ativos · prazos, cobranças e acompanhamento</small></span></div><div className="portfolioOverviewMetrics"><span className="healthy"><b>{activeHealth.filter(item=>item.level==='healthy').length}</b><small>Em dia</small></span><span className="attention"><b>{activeHealth.filter(item=>item.level==='attention').length}</b><small>Atenção</small></span><span className="critical"><b>{activeHealth.filter(item=>item.level==='critical').length}</b><small>Críticos</small></span><span><b>{money(atRiskRevenue)}</b><small>Receita mensal em atenção</small></span></div></section>
  <div className={'clientWorkspace '+(selected?'hasDetails':'')}><section className="card clientTablePanel"><CompactFilters label="Filtros de clientes" query={query} onQuery={setQuery} placeholder="Buscar cliente..." primary={<><div className="tabs">{[['all','Todos'],['active','Ativos'],['inactive','Inativos'],['prospect','Prospects']].map(([value,label])=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{label}</button>)}</div></>} secondary={<label><span>Saúde da carteira</span><select aria-label="Filtrar por saúde da carteira" value={healthFilter} onChange={event=>setHealthFilter(event.target.value as ClientHealthLevel|'all')}><option value="all">Toda a carteira</option><option value="critical">Críticos</option><option value="attention">Precisam de atenção</option><option value="healthy">Em dia</option></select></label>} secondaryCount={healthFilter==='all'?0:1} chips={[
 ...(query?[{id:'query',label:`Busca: ${query}`,onRemove:()=>setQuery('')}]:[]),
 ...(tab!=='all'?[{id:'status',label:`Status: ${({active:'Ativos',inactive:'Inativos',prospect:'Prospects'} as Record<string,string>)[tab]}`,onRemove:()=>setTab('all')}]:[]),
 ...(healthFilter!=='all'?[{id:'health',label:`Saúde: ${clientHealthLabel[healthFilter]}`,onRemove:()=>setHealthFilter('all')}]:[])
 ]} onClear={()=>{setQuery('');setTab('all');setHealthFilter('all')}} result={<>{filtered.length} de {clients.length} clientes</>}/><div className="tableWrap"><table><thead><tr><th>Cliente</th><th>Contato principal</th><th>Serviços contratados</th><th>Status</th><th>Saúde</th><th>Projetos</th><th>Receita mensal</th></tr></thead><tbody>{filtered.map(client=>{const names=serviceNames(client),health=healthById.get(client.id)!;return <tr key={client.id} onClick={()=>setSelected(client)}><td><div className="entity"><span className="avatar" style={{background:client.color}}>{initials(client.companyName)}</span><span><b>{client.companyName}</b><small>{client.instagram}</small></span></div></td><td><b>{client.contactName}</b><small className="block">{client.email}</small></td><td>{names.length?names.slice(0,2).map(name=><span className="tag" key={name}>{name}</span>):'—'}</td><td><span className={'badge '+(client.status==='active'?'green':client.status==='prospect'?'orange':'red')}>{client.status==='active'?'Ativo':client.status==='prospect'?'Prospecção':'Inativo'}</span></td><td><span className={`clientHealthBadge ${health.level}`} title={health.signals.map(signal=>signal.label).join(' · ')}>{clientHealthLabel[health.level]}{health.score!==null&&` · ${health.score}`}</span></td><td>{projects.filter(project=>project.clientId===client.id).length}</td><td>{money(client.monthlyRevenue)}</td></tr>})}</tbody></table>{!filtered.length&&<p className="portfolioEmpty">Nenhum cliente corresponde aos filtros selecionados.</p>}</div></section>{selected&&<ClientDetails client={selected} health={healthById.get(selected.id)} services={services} projects={projects} onClose={()=>setSelected(null)} onTask={()=>setTaskClient(selected)}/>}</div>
  {creating&&<ClientForm client={null} services={services} onSubmit={submit} onClose={()=>setCreating(false)}/>}{taskClient&&<ClientTaskModal client={taskClient} onClose={()=>setTaskClient(null)}/>}</main>
}

function ClientDetails({client,health,services,projects,onClose,onTask}:{client:Client;health?:ClientHealth;services:AgencyService[];projects:Project[];onClose:()=>void;onTask:()=>void}){
 const linked=linkedServices(client,services),team=store.get<TeamMember[]>('team',[]),responsible=team.filter(member=>(client.responsibleIds||[client.managerId]).includes(member.id));
 return <aside className="details card clientEnhancedDetails"><button className="iconBtn close" onClick={onClose}><X/></button><div className="detailHero"><span className="avatar" style={{background:client.color}}>{initials(client.companyName)}</span><div><h3>{client.companyName}</h3><p>{client.cnpj||client.instagram}</p><span className={'badge '+(client.status==='active'?'green':client.status==='prospect'?'orange':'red')}>{client.status==='active'?'Ativo':client.status==='prospect'?'Prospect':'Inativo'}</span></div></div><a className="btn clientHubButton" href={`/clients/${client.id}`}>Abrir central do cliente</a><div className="detailBtns clientPreviewActions"><button className="btn" onClick={onTask} disabled={client.status!=='active'}><Plus/> Nova tarefa</button></div>
  {health?.score!==null&&health&&<div className="detailBox clientHealthPreview"><h4>Saúde da conta <span className={`clientHealthBadge ${health.level}`}>{clientHealthLabel[health.level]} · {health.score}</span></h4>{health.signals.length?health.signals.map(signal=><p key={signal.label}>{signal.label}</p>):<p>Sem alertas operacionais no momento.</p>}</div>}
  <div className="detailBox"><h4>Visão geral</h4><p><span>CNPJ</span><b>{client.cnpj||'Não informado'}</b></p><p><span>Dia do pagamento</span><b>{client.paymentDay?`Dia ${client.paymentDay}`:'Não definido'}</b></p><p><span>Receita mensal</span><b>{money(client.monthlyRevenue)}</b></p><p><span>Projetos</span><b>{projects.filter(project=>project.clientId===client.id).length}</b></p></div><div className="detailBox clientResponsibleBox"><h4>Pessoas responsáveis</h4>{responsible.length?responsible.map(member=><p key={member.id}><span>{member.name}</span><b>{member.roles?.join(', ')||member.role}</b></p>):<p>Nenhuma pessoa selecionada.</p>}</div><div className="detailBox"><h4>Serviços contratados</h4>{linked.length?linked.map(service=><p key={service.id}><span>{service.name}</span><b className="greenText">{service.active?'Ativo':'Inativo'}</b></p>):<p>Nenhum serviço selecionado.</p>}</div></aside>
}

function Stat({icon,label,value,tone='' }:{icon:any;label:string;value:string;tone?:string}){return <article><span className={'clientStatIcon '+tone}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>Atualizado agora</em></div></article>}
