import {BrainCircuit,GitBranch,Network,Pencil,Plus,Save,Trash2,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {layoutMindMapNodes,mindMapRoot,removeMindMapBranch,type ClientMindMap,type ClientMindMapNode} from './client-mind-maps';
import './client-mind-maps.css';

type Props={clientId:string;maps:ClientMindMap[];onChange:(maps:ClientMindMap[])=>void};
type MapDraft={id?:string;title:string;description:string;rootText:string;createdAt?:string};
const colors=['#5b36f2','#2563eb','#059669','#d97706','#dc2626','#db2777','#0891b2','#475569'];

export default function ClientMindMapsPanel({clientId,maps,onChange}:Props){
 const [selectedId,setSelectedId]=useState(maps[0]?.id||''),[selectedNodeId,setSelectedNodeId]=useState(''),[nodeText,setNodeText]=useState(''),[branchText,setBranchText]=useState(''),[draft,setDraft]=useState<MapDraft|null>(null);
 const selected=maps.find(map=>map.id===selectedId)||maps[0],root=selected?mindMapRoot(selected.nodes):undefined,selectedNode=selected?.nodes.find(node=>node.id===selectedNodeId),positioned=useMemo(()=>layoutMindMapNodes(selected?.nodes||[]),[selected]);
 useEffect(()=>{if(!maps.length){setSelectedId('');setSelectedNodeId('');return}if(!maps.some(map=>map.id===selectedId))setSelectedId(maps[0].id)},[maps,selectedId]);
 useEffect(()=>{const node=selected?.nodes.find(item=>item.id===selectedNodeId)||root;if(node){setSelectedNodeId(node.id);setNodeText(node.text)}},[selected?.id,selectedNodeId,root?.id]);

 const updateMap=(map:ClientMindMap)=>onChange(maps.map(item=>item.id===map.id?map:item));
 const openNew=()=>setDraft({title:'',description:'',rootText:''});
 const openEdit=()=>selected&&setDraft({id:selected.id,title:selected.title,description:selected.description,rootText:root?.text||selected.title,createdAt:selected.createdAt});
 const saveMap=(event:React.FormEvent)=>{event.preventDefault();if(!draft)return;const now=new Date().toISOString(),title=draft.title.trim(),rootText=draft.rootText.trim()||title;if(!title||!rootText)return;if(draft.id&&selected){const rootId=root?.id,updated={...selected,title,description:draft.description.trim(),updatedAt:now,nodes:selected.nodes.map(node=>node.id===rootId?{...node,text:rootText}:node)};updateMap(updated);setSelectedId(updated.id)}else{const map:ClientMindMap={id:crypto.randomUUID(),clientId,title,description:draft.description.trim(),nodes:[{id:crypto.randomUUID(),parentId:null,text:rootText,color:colors[0]}],createdAt:now,updatedAt:now};onChange([map,...maps]);setSelectedId(map.id);setSelectedNodeId(map.nodes[0].id)}setDraft(null)};
 const selectNode=(node:ClientMindMapNode)=>{setSelectedNodeId(node.id);setNodeText(node.text)};
 const saveNode=()=>{if(!selected||!selectedNode||!nodeText.trim())return;updateMap({...selected,updatedAt:new Date().toISOString(),nodes:selected.nodes.map(node=>node.id===selectedNode.id?{...node,text:nodeText.trim()}:node)})};
 const setNodeColor=(color:string)=>{if(!selected||!selectedNode)return;updateMap({...selected,updatedAt:new Date().toISOString(),nodes:selected.nodes.map(node=>node.id===selectedNode.id?{...node,color}:node)})};
 const addBranch=(event:React.FormEvent)=>{event.preventDefault();if(!selected||!branchText.trim())return;const parentId=selectedNode?.id||root?.id;if(!parentId)return;const node:ClientMindMapNode={id:crypto.randomUUID(),parentId,text:branchText.trim(),color:colors[(selected.nodes.length)%colors.length]};updateMap({...selected,updatedAt:new Date().toISOString(),nodes:[...selected.nodes,node]});setBranchText('');setSelectedNodeId(node.id);setNodeText(node.text)};
 const deleteBranch=()=>{if(!selected||!selectedNode||selectedNode.parentId===null)return;if(confirm(`Excluir “${selectedNode.text}” e suas ramificações?`)){const nodes=removeMindMapBranch(selected.nodes,selectedNode.id);updateMap({...selected,nodes,updatedAt:new Date().toISOString()});setSelectedNodeId(root?.id||'')}};
 const deleteMap=()=>{if(selected&&confirm(`Excluir o mapa mental “${selected.title}”?`)){const next=maps.filter(map=>map.id!==selected.id);onChange(next);setSelectedId(next[0]?.id||'')}};

 return <section className="mindMapsWorkspace">
  <div className="mindMapsHead"><div><span><BrainCircuit/></span><div><h3>Mapas mentais</h3><p>Organize ideias, estratégias e ramificações específicas deste cliente.</p></div></div><button type="button" className="btn" onClick={openNew}><Plus/> Novo mapa</button></div>
  {!maps.length?<div className="card mindMapsEmpty"><BrainCircuit/><h3>Nenhum mapa mental criado</h3><p>Crie um mapa para estruturar campanhas, estratégias, públicos, conteúdos ou qualquer fluxo de ideias.</p><button type="button" className="btn secondary" onClick={openNew}><Plus/> Criar primeiro mapa</button></div>:<div className="mindMapsLayout">
   <aside className="card mindMapList"><header><b>Seus mapas</b><span>{maps.length}</span></header>{maps.map(map=><button type="button" className={map.id===selected?.id?'active':''} key={map.id} onClick={()=>{setSelectedId(map.id);setSelectedNodeId('')}}><span><Network/></span><div><b>{map.title}</b><small>{map.nodes.length} {map.nodes.length===1?'tópico':'tópicos'}</small></div></button>)}</aside>
   {selected&&<div className="mindMapMain"><div className="card mindMapToolbar"><div><h4>{selected.title}</h4><p>{selected.description||'Mapa mental do cliente'}</p></div><div><button type="button" onClick={openEdit}><Pencil/> Editar mapa</button><button type="button" className="danger" onClick={deleteMap}><Trash2/> Excluir</button></div></div>
    <div className="card mindMapCanvasScroll"><div className="mindMapCanvas"><svg viewBox="0 0 1080 620" aria-hidden="true">{positioned.filter(node=>node.parentId).map(node=>{const parent=positioned.find(item=>item.id===node.parentId);return parent?<line key={node.id} x1={parent.x} y1={parent.y} x2={node.x} y2={node.y}/>:null})}</svg>{positioned.map(node=><button type="button" key={node.id} className={`mindMapNode${node.id===selectedNode?.id?' selected':''}${node.parentId===null?' root':''}`} style={{left:node.x,top:node.y,borderColor:node.color,'--node-color':node.color} as React.CSSProperties} onClick={()=>selectNode(node)}><span>{node.parentId===null?<BrainCircuit/>:<GitBranch/>}</span><b>{node.text}</b></button>)}</div></div>
    {selectedNode&&<section className="card mindMapInspector"><div className="mindMapNodeEditor"><div><small>{selectedNode.parentId===null?'TÓPICO CENTRAL':'RAMIFICAÇÃO SELECIONADA'}</small><b>Editar tópico</b></div><input value={nodeText} onChange={event=>setNodeText(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')saveNode()}}/><button type="button" onClick={saveNode} disabled={!nodeText.trim()}><Save/> Salvar</button></div><div className="mindMapColors"><span>Cor</span>{colors.map(color=><button type="button" aria-label={`Usar cor ${color}`} className={selectedNode.color===color?'active':''} key={color} style={{background:color}} onClick={()=>setNodeColor(color)}/>)}</div><form className="mindMapAddBranch" onSubmit={addBranch}><label><span>Nova ramificação em <b>{selectedNode.text}</b></span><input value={branchText} onChange={event=>setBranchText(event.target.value)} placeholder="Digite uma nova ideia..."/></label><button className="btn" disabled={!branchText.trim()}><Plus/> Adicionar</button></form>{selectedNode.parentId!==null&&<button type="button" className="mindMapDeleteBranch" onClick={deleteBranch}><Trash2/> Excluir esta ramificação</button>}</section>}
   </div>}
  </div>}
  {draft&&<div className="overlay"><div className="modal mindMapModal" role="dialog" aria-modal="true" aria-labelledby="mind-map-dialog-title"><div className="modalHead"><div><small>MAPA MENTAL</small><h2 id="mind-map-dialog-title">{draft.id?'Editar mapa mental':'Novo mapa mental'}</h2><p>Comece pelo assunto principal e depois adicione as ramificações.</p></div><button type="button" className="iconBtn" aria-label="Fechar" onClick={()=>setDraft(null)}><X/></button></div><form className="form" onSubmit={saveMap}><label className="full">Nome do mapa<input autoFocus required value={draft.title} onChange={event=>setDraft(current=>current?{...current,title:event.target.value}:current)} placeholder="Ex.: Estratégia de lançamento"/></label><label className="full">Descrição<textarea value={draft.description} onChange={event=>setDraft(current=>current?{...current,description:event.target.value}:current)} placeholder="Objetivo ou contexto deste mapa"/></label><label className="full">Tópico central<input required value={draft.rootText} onChange={event=>setDraft(current=>current?{...current,rootText:event.target.value}:current)} placeholder="Ex.: Lançamento do produto"/></label><div className="formActions full"><button type="button" className="btn secondary" onClick={()=>setDraft(null)}>Cancelar</button><button className="btn" disabled={!draft.title.trim()||!draft.rootText.trim()}>{draft.id?'Salvar alterações':'Criar mapa'}</button></div></form></div></div>}
 </section>;
}
