import {useEffect,useMemo,useState} from 'react';
import {BarChart3,CalendarDays,Funnel,GripVertical,Plus,Target,TrendingUp,Trophy,UserRound,X} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {store} from './storage';
import type {AgencyService} from './ServicesManager';
import type {TeamMember} from './types';
import {crmStages as stages,serviceEstimate,type CRMLead as Lead,type CRMStage as Stage} from './crm-leads';
import './crm-funnel.css';

type FunnelItem={stage:string;fullStage:Stage;leads:number;percentage:number;color:string};

const palette=['#5b36f2','#287cf0','#16a269','#e99a18','#e8547c','#7c8aa2','#0e9f6e','#e04a52'];
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default function CRMPage(){
 const [leads,setLeads]=useState<Lead[]>(()=>store.get('prospects',[]));
 const [services,setServices]=useState<AgencyService[]>(()=>store.get('services',[]));
 const [team,setTeam]=useState<TeamMember[]>(()=>store.get('team',[]));
 const [modal,setModal]=useState(false);
 const [dragged,setDragged]=useState<string|null>(null);
 const [selectedServiceIds,setSelectedServiceIds]=useState<string[]>([]);
 const [variableEstimate,setVariableEstimate]=useState(0);

 useEffect(()=>{const update=()=>{setLeads(store.get('prospects',[]));setServices(store.get('services',[]));setTeam(store.get('team',[]))};window.addEventListener('roas-change',update);return()=>window.removeEventListener('roas-change',update)},[]);
 const save=(next:Lead[])=>{setLeads(next);store.set('prospects',next)};
 const move=(stage:Stage)=>{if(dragged)save(leads.map(l=>l.id===dragged?{...l,stage}:l));setDragged(null)};
 const estimate=serviceEstimate(selectedServiceIds,services),estimatedValue=estimate.fixedValue+(estimate.hasVariable||!selectedServiceIds.length?variableEstimate:0);
 const openModal=()=>{setSelectedServiceIds([]);setVariableEstimate(0);setModal(true)};
 const closeModal=()=>{setModal(false);setSelectedServiceIds([]);setVariableEstimate(0)};
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget),now=new Date().toISOString();save([{id:crypto.randomUUID(),name:String(form.get('name')).trim(),contact:String(form.get('contact')).trim(),phone:String(form.get('phone')).trim(),responsibleId:String(form.get('responsibleId')),value:estimatedValue,stage:'Leads captados',source:String(form.get('source')),nextAction:'Fazer primeiro contato',color:palette[leads.length%palette.length],serviceIds:selectedServiceIds,createdAt:now,updatedAt:now},...leads]);closeModal()};

 const funnel=useMemo<FunnelItem[]>(()=>stages.map((stage,index)=>{const count=leads.filter(l=>l.stage===stage).length;return{stage:stage.length>15?stage.split(' ')[0]:stage,fullStage:stage,leads:count,percentage:leads.length?Math.round(count/leads.length*100):0,color:palette[index]}}),[leads]);
 const sources=useMemo(()=>Array.from(new Set(leads.map(l=>l.source))).map(source=>({name:source,value:leads.filter(l=>l.source===source).length})),[leads]);
 const active=leads.filter(l=>!['Negócio fechado','Negócio perdido'].includes(l.stage));
 const won=leads.filter(l=>l.stage==='Negócio fechado');
 const conversion=leads.length?Math.round(won.length/leads.length*100):0;
 const trend=useMemo(()=>Array.from({length:12},(_,index)=>{const end=new Date();end.setHours(23,59,59,999);end.setDate(end.getDate()-(11-index)*7);const start=new Date(end);start.setDate(start.getDate()-6);start.setHours(0,0,0,0);return{week:`S${index+1}`,leads:leads.filter(lead=>{if(!lead.createdAt)return false;const createdAt=new Date(lead.createdAt);return createdAt>=start&&createdAt<=end}).length}}),[leads]);

 return <main className="crmPage">
  <div className="crmPageTitle"><div><h2>CRM de Prospecção</h2><p>Acompanhe oportunidades, serviços solicitados e a saúde do funil.</p></div><button className="btn" onClick={openModal}><Plus/> Novo lead</button></div>
  <div className="crmKpis"><Kpi icon={<Target/>} label="Oportunidades ativas" value={String(active.length)} note="Em negociação"/><Kpi icon={<TrendingUp/>} label="Valor no pipeline" value={money(active.reduce((s,l)=>s+l.value,0))} note="Potencial de receita" tone="blue"/><Kpi icon={<Trophy/>} label="Negócios fechados" value={String(won.length)} note={money(won.reduce((s,l)=>s+l.value,0))} tone="green"/><Kpi icon={<BarChart3/>} label="Conversão" value={`${conversion}%`} note="Do total de leads" tone="orange"/></div>
  <section className="card crmPageBoard">
   <div className="crmBoardLabel"><div><b>Pipeline comercial</b><span>Arraste os cartões para atualizar a etapa</span></div><small>{leads.length} oportunidades</small></div>
   <div className="crmColumns">{stages.map((stage,index)=><div className="crmColumn" key={stage} onDragOver={e=>e.preventDefault()} onDrop={()=>move(stage)}><header style={{borderBottom:`2px solid ${palette[index]}`}}><b>{stage}</b><span>{leads.filter(l=>l.stage===stage).length}</span></header><div className="crmCards">{leads.filter(l=>l.stage===stage).map(lead=>{const linked=services.filter(service=>lead.serviceIds?.includes(service.id)||lead.services?.includes(service.name));return <article className="leadCard" data-lead-id={lead.id} key={lead.id} draggable onDragStart={()=>setDragged(lead.id)}><div className="leadTop"><i style={{background:lead.color}}>{lead.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><GripVertical/></div><h3>{lead.name}</h3><p><UserRound/>{lead.contact}</p>{linked.length?<div className="leadServices">{linked.slice(0,2).map(service=><span key={service.id}>{service.name}</span>)}{linked.length>2&&<span>+{linked.length-2}</span>}</div>:null}<strong>{money(lead.value)}</strong><footer><span>{lead.source}</span><small><CalendarDays/>{lead.nextAction}</small></footer></article>})}</div><button className="addLead" onClick={openModal}>＋ Adicionar lead</button></div>)}</div>
  </section>
  <FunnelOverview data={funnel} total={leads.length} conversion={conversion}/>
  <div className="crmAnalytics">
   <Chart title="Visão do funil" subtitle="Quantidade de oportunidades por etapa"><ResponsiveContainer width="100%" height={260}><BarChart data={funnel}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="stage" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="leads" radius={[5,5,0,0]}>{funnel.map(x=><Cell fill={x.color} key={x.fullStage}/>)}</Bar></BarChart></ResponsiveContainer></Chart>
   <section className="card crmChart"><div className="chartTitle"><h3>Origem dos leads</h3><p>Canais que geram oportunidades</p></div><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={sources} dataKey="value" nameKey="name" innerRadius={48} outerRadius={78}>{sources.map((s,i)=><Cell fill={palette[i%palette.length]} key={s.name}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="sourceLegend">{sources.map((s,i)=><span key={s.name}><i style={{background:palette[i%palette.length]}}/>{s.name}<b>{s.value}</b></span>)}</div></section>
   <Chart title="Evolução da prospecção" subtitle="Leads captados nas últimas 12 semanas" last><ResponsiveContainer width="100%" height={230}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="week"/><YAxis/><Tooltip/><Line dataKey="leads" type="monotone" stroke="#5b36f2" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart>
  </div>
  {modal&&<div className="overlay"><div className="modal crmModal"><div className="modalHead"><div><small>NOVO LEAD</small><h2>Adicionar oportunidade</h2><p>Cadastre o contato, o responsável e os serviços solicitados.</p></div><button className="iconBtn" onClick={closeModal}><X/></button></div><form className="form" onSubmit={add}><label>Empresa<input name="name" required autoFocus/></label><label>Contato<input name="contact" required/></label><label>Telefone<input name="phone" type="tel" placeholder="(00) 00000-0000"/></label><label>Responsável pelo lead<select name="responsibleId"><option value="">Definir depois</option>{team.filter(member=>member.status==='active').map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Origem<select name="source"><option>Instagram</option><option>Site</option><option>Indicação</option><option>Google</option><option>WhatsApp</option></select></label><div className="full"><b className="formGroupLabel">Serviços solicitados</b><small className="formHelper">Serviços mensais entram automaticamente no valor estimado.</small><div className="selectionGrid crmServicesSelect">{services.filter(service=>service.active).map(service=><label key={service.id}><input type="checkbox" checked={selectedServiceIds.includes(service.id)} onChange={event=>setSelectedServiceIds(current=>event.target.checked?[...current,service.id]:current.filter(id=>id!==service.id))}/><span><b>{service.name}</b><small>{service.pricingType==='variable'||service.price<=0?'Valor a definir':`${money(service.price)}/mês`}</small></span></label>)}</div>{!services.length&&<p className="noServices">Cadastre serviços em Configurações → Serviços.</p>}</div><div className="leadEstimateBox full"><div><span>Valor automático dos serviços</span><strong>{money(estimate.fixedValue)}</strong></div>{(estimate.hasVariable||!selectedServiceIds.length)&&<label>{selectedServiceIds.length?'Estimativa dos serviços sem valor fixo':'Valor estimado'}<input type="number" min="0" step="0.01" value={variableEstimate||''} onChange={event=>setVariableEstimate(Number(event.target.value)||0)} placeholder="0,00"/><small>{selectedServiceIds.length?'Adicione uma estimativa para os serviços de valor variável.':'Selecione serviços ou informe uma estimativa manual.'}</small></label>}<div className="leadEstimateTotal"><span>Valor estimado total</span><strong>{money(estimatedValue)}</strong></div></div><div className="formActions full"><button type="button" className="btn secondary" onClick={closeModal}>Cancelar</button><button className="btn">Adicionar ao CRM</button></div></form></div></div>}
 </main>
}

function FunnelOverview({data,total,conversion}:{data:FunnelItem[];total:number;conversion:number}){return <section className="card crmFunnelOverview"><div className="crmFunnelHeader"><div><span className="crmFunnelTitleIcon"><Funnel/></span><div><h3>Funil de oportunidades</h3><p>Percentual de leads em cada etapa do pipeline atual</p></div></div><span className="crmFunnelTotal"><b>{total}</b> leads no total</span></div><div className="crmFunnelBody"><div className="crmFunnelShape">{data.map((item,index)=><div className="crmFunnelStep" key={item.fullStage} style={{width:`${Math.max(46,100-index*7.5)}%`,background:item.color}}><span>{item.fullStage}</span><strong>{item.percentage}%</strong><small>{item.leads} {item.leads===1?'lead':'leads'}</small></div>)}</div><div className="crmFunnelBreakdown">{data.map(item=><div className="crmFunnelMetric" key={item.fullStage}><div><i style={{background:item.color}}/><span>{item.fullStage}</span><b>{item.leads}</b></div><div className="crmFunnelProgress"><span style={{width:`${item.percentage}%`,background:item.color}}/></div><small>{item.percentage}% do total</small></div>)}<div className="crmFunnelConversion"><span>Conversão final</span><strong>{conversion}%</strong><small>Leads totais → negócios fechados</small></div></div></div></section>}
function Kpi({icon,label,value,note,tone='' }:{icon:any;label:string;value:string;note:string;tone?:string}){return <article><span className={'crmKpiIcon '+tone}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>}
function Chart({title,subtitle,children,last=false}:{title:string;subtitle:string;children:any;last?:boolean}){return <section className={'card crmChart wide '+(last?'last':'')}><div className="chartTitle"><h3>{title}</h3><p>{subtitle}</p></div>{children}</section>}
