import {ArrowRight,BarChart3,CheckCircle2,FileText,PlugZap,RefreshCw,TriangleAlert,Users} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useStoreData} from './app/useStoreData';
import {marketingProviders,normalizeClientMarketingIntegrations,type ClientMarketingIntegration} from './marketing-integrations';
import {aggregateMarketingMetrics,normalizeMarketingMetricsSnapshots,type MarketingMetricsSnapshot} from './marketing-metrics';
import type {Client,GenericItem} from './types';
import './marketing-metrics.css';

export default function MarketingDashboardPage(){
 const [clients]=useStoreData<Client[]>('clients',[]),[storedIntegrations]=useStoreData<ClientMarketingIntegration[]>('client_marketing_integrations',[]),[storedMetrics]=useStoreData<MarketingMetricsSnapshot[]>('marketing_metrics',[]),[reports]=useStoreData<GenericItem[]>('reports',[]),integrations=normalizeClientMarketingIntegrations(storedIntegrations);
 const activeClients=clients.filter(client=>client.status==='active'),activeIds=new Set(activeClients.map(client=>client.id)),connected=integrations.filter(item=>item.status==='connected'&&activeIds.has(item.clientId)),integratedBrands=new Set(connected.map(item=>item.clientId)).size;
 const pendingBrands=Math.max(0,activeClients.length-integratedBrands),coverage=activeClients.length?Math.round(integratedBrands/activeClients.length*100):0;
 const recentSync=[...connected].filter(item=>item.lastSync).sort((a,b)=>String(b.lastSync).localeCompare(String(a.lastSync))).slice(0,5);
 const connectedIds=new Set(connected.map(item=>item.id)),metricsSnapshots=normalizeMarketingMetricsSnapshots(storedMetrics).filter(item=>connectedIds.has(item.integrationId)),metrics=aggregateMarketingMetrics(metricsSnapshots),hasMetrics=metricsSnapshots.length>0;
 return <main className="marketingDashboardPage">
  <section className="marketingDashboardHero"><div><span><BarChart3/> DASHBOARD DE MARKETING</span><h2>Visão consolidada das marcas</h2><p>Acompanhe a cobertura das integrações e prepare os canais que alimentarão os indicadores de mídia.</p></div><div><Link className="btn" to="/marketing/integrations"><PlugZap/> Configurar integrações</Link><Link className="btn secondary" to="/marketing/reports"><FileText/> Abrir relatórios</Link></div></section>
  <section className="marketingDashboardStats"><MarketingStat icon={<Users/>} label="Marcas ativas" value={activeClients.length} note="Clientes ativos"/><MarketingStat icon={<CheckCircle2/>} label="Marcas integradas" value={integratedBrands} note={`${coverage}% da carteira`} tone="green"/><MarketingStat icon={<PlugZap/>} label="Canais vinculados" value={connected.length} note={`${marketingProviders.length} plataformas disponíveis`} tone="blue"/><MarketingStat icon={<TriangleAlert/>} label="Aguardando configuração" value={pendingBrands} note="Marcas sem nenhum canal" tone="orange"/><MarketingStat icon={<FileText/>} label="Relatórios" value={reports.length} note="Registros disponíveis" tone="purple"/></section>
  <section className="marketingRealMetrics" aria-label="Resultados sincronizados de mídia">{hasMetrics?<><Metric label="Investimento" value={currency(metrics.spend)}/><Metric label="Impressões" value={integer(metrics.impressions)}/><Metric label="Cliques" value={integer(metrics.clicks)}/><Metric label="Conversões" value={decimal(metrics.conversions)}/><Metric label="Valor de conversão" value={currency(metrics.conversionValue)}/><Metric label="ROAS" value={`${decimal(metrics.roas)}x`}/></>:<div className="marketingMetricsEmpty">Sincronize uma conta de Meta Ads ou Google Ads para visualizar os resultados reais do mês.</div>}</section>
  <div className="marketingDashboardGrid"><section className="card marketingCoveragePanel"><div className="marketingPanelHead"><div><h3>Cobertura por marca</h3><p>Canais configurados para cada cliente ativo</p></div><Link to="/marketing/integrations">Gerenciar <ArrowRight/></Link></div><div className="marketingBrandRows">{activeClients.map(client=>{const total=connected.filter(item=>item.clientId===client.id).length;return <article key={client.id}><span className="avatar" style={{background:client.color}}>{initials(client.companyName)}</span><div><b>{client.companyName}</b><span>{total} de {marketingProviders.length} canais</span></div><div className="marketingProviderDots">{marketingProviders.map(provider=><i key={provider.id} className={connected.some(item=>item.clientId===client.id&&item.provider===provider.id)?'active':''} title={provider.name}>{provider.mark}</i>)}</div><strong>{Math.round(total/marketingProviders.length*100)}%</strong></article>})}{!activeClients.length&&<p className="marketingEmpty">Cadastre um cliente ativo para começar.</p>}</div></section>
  <section className="card marketingSyncPanel"><div className="marketingPanelHead"><div><h3>Sincronizações recentes</h3><p>Últimas atualizações registradas</p></div><RefreshCw/></div><div>{recentSync.map(item=>{const client=clients.find(client=>client.id===item.clientId),provider=marketingProviders.find(provider=>provider.id===item.provider);return <article key={item.id}><span>{provider?.mark}</span><div><b>{provider?.name}</b><small>{client?.companyName}</small></div><time>{formatDate(item.lastSync)}</time></article>})}{!recentSync.length&&<p className="marketingEmpty">Nenhuma sincronização registrada.</p>}</div></section></div>
  <section className="marketingDataNotice"><BarChart3/><div><b>{hasMetrics?'Dados reais conectados':'Conecte seus dados de mídia'}</b><span>{hasMetrics?`Indicadores consolidados de ${metricsSnapshots.length} ${metricsSnapshots.length===1?'conta sincronizada':'contas sincronizadas'} no período atual.`:'Depois de vincular uma conta, use “Sincronizar agora” para carregar investimento, cliques, conversões e ROAS.'}</span></div></section>
 </main>;
}

function MarketingStat({icon,label,value,note,tone='' }:{icon:React.ReactNode;label:string;value:number;note:string;tone?:string}){return <article className="card"><span className={`integrationStatIcon ${tone||'purple'}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>}
function Metric({label,value}:{label:string;value:string}){return <article className="card"><small>{label}</small><strong>{value}</strong></article>}
const initials=(name:string)=>name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();
const formatDate=(value?:string)=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
const currency=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const integer=(value:number)=>Math.round(value).toLocaleString('pt-BR');
const decimal=(value:number)=>value.toLocaleString('pt-BR',{maximumFractionDigits:2});
