import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,BarChart3,CalendarRange,ChevronRight,FileText,GripVertical,Layers3,MousePointerClick,PlugZap,RefreshCw,Search,Settings2,SlidersHorizontal,Target,TrendingUp,WalletCards,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useStoreData} from './app/useStoreData';
import {defaultMarketingMetricIds,defaultMarketingPerformanceTable,formatMarketingMetric,marketingMetricCatalog,metricValue,normalizeMarketingDashboardPreferences,type MarketingDashboardPreference,type MarketingDashboardWidget,type MarketingMetricKey,type MarketingPerformanceTablePreference} from './marketing-dashboard-config';
import MarketingDashboardWidgets from './MarketingDashboardWidgets';
import {markMarketingIntegrationSynced,marketingProviders,normalizeClientMarketingIntegrations,type ClientMarketingIntegration} from './marketing-integrations';
import {aggregateMarketingMetrics,emptyMarketingMetrics,normalizeMarketingMetricsSnapshots,upsertMarketingMetricsSnapshot,type MarketingMetricsSnapshot,type MarketingPerformanceLevel,type MarketingPerformanceRow} from './marketing-metrics';
import {syncMarketingMetrics} from './marketing-oauth-client';
import {marketingPeriodOptions,marketingPeriodRange,normalizeMarketingPeriodKey,type MarketingPeriodKey} from './marketing-period';
import {usePersistentState} from './persistent-ui';
import type {Client} from './types';
import './marketing-metrics.css';

type ProviderFilter='all'|'meta_ads'|'google_ads';

export default function MarketingDashboardPage(){
 const [clients]=useStoreData<Client[]>('clients',[]);
 const [storedIntegrations,setStoredIntegrations]=useStoreData<ClientMarketingIntegration[]>('client_marketing_integrations',[]);
 const [storedMetrics,setStoredMetrics]=useStoreData<MarketingMetricsSnapshot[]>('marketing_metrics',[]);
 const [storedPreferences,setPreferences]=useStoreData<MarketingDashboardPreference[]>('marketing_dashboard_preferences',[]);
 const integrations=useMemo(()=>normalizeClientMarketingIntegrations(storedIntegrations).filter((item):item is ClientMarketingIntegration&{provider:'meta_ads'|'google_ads'}=>item.status==='connected'&&(item.provider==='meta_ads'||item.provider==='google_ads')),[storedIntegrations]);
 const snapshots=useMemo(()=>normalizeMarketingMetricsSnapshots(storedMetrics),[storedMetrics]);
 const integratedClients=useMemo(()=>clients.filter(client=>client.status==='active'&&integrations.some(item=>item.clientId===client.id)),[clients,integrations]);
 const [clientId,setClientId]=usePersistentState('roas_filter_marketing_dashboard_client',integratedClients[0]?.id||'');
 const [providerFilter,setProviderFilter]=usePersistentState<ProviderFilter>('roas_filter_marketing_dashboard_provider','all');
 const [periodKey,setPeriodKey]=usePersistentState<MarketingPeriodKey>('roas_filter_marketing_dashboard_period','this_month');
 const [customizing,setCustomizing]=useState(false),[draftMetrics,setDraftMetrics]=useState<MarketingMetricKey[]>([]),[configuringTable,setConfiguringTable]=useState(false);
 const [metricSearch,setMetricSearch]=useState('');
 const [syncing,setSyncing]=useState(false),[syncError,setSyncError]=useState('');
 useEffect(()=>{if(!integratedClients.some(client=>client.id===clientId))setClientId(integratedClients[0]?.id||'')},[clientId,integratedClients,setClientId]);
 const selectedClient=integratedClients.find(client=>client.id===clientId);
 const clientIntegrations=integrations.filter(item=>item.clientId===clientId);
 const visibleIntegrations=clientIntegrations.filter(item=>providerFilter==='all'||item.provider===providerFilter);
 const visibleIds=new Set(visibleIntegrations.map(item=>item.id));
 const visibleSnapshots=snapshots.filter(item=>visibleIds.has(item.integrationId));
 const metrics=visibleSnapshots.length?aggregateMarketingMetrics(visibleSnapshots):emptyMarketingMetrics;
 const preferences=normalizeMarketingDashboardPreferences(storedPreferences);
 const clientPreference=preferences.find(item=>item.clientId===clientId),metricIds=clientPreference?.metricIds||defaultMarketingMetricIds,widgets=clientPreference?.widgets||[],performanceTable=clientPreference?.performanceTable||defaultMarketingPerformanceTable;
 const performanceRows=visibleSnapshots.flatMap(snapshot=>snapshot.performanceRows.map(row=>({...row,key:`${snapshot.integrationId}:${row.level}:${row.id}`}))).filter(row=>row.level===performanceTable.level).sort((a,b)=>metricValue(b,performanceTable.metricIds[0])-metricValue(a,performanceTable.metricIds[0])).slice(0,10);
 const metricQuery=metricSearch.trim().toLocaleLowerCase('pt-BR');
 const filteredMetricCatalog=marketingMetricCatalog.filter(metric=>!metricQuery||`${metric.label} ${metric.description} ${metric.category}`.toLocaleLowerCase('pt-BR').includes(metricQuery));
 const metricCategories=[...new Set(marketingMetricCatalog.map(metric=>metric.category))];
 const period=visibleSnapshots.length?`${date(visibleSnapshots.map(item=>item.periodFrom).sort()[0])} até ${date(visibleSnapshots.map(item=>item.periodTo).sort().at(-1))}`:'Sem período sincronizado';
 const openCustomization=()=>{setDraftMetrics([...metricIds]);setMetricSearch('');setCustomizing(true)};
 const toggleMetric=(id:MarketingMetricKey)=>setDraftMetrics(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const moveDraftMetric=(index:number,direction:-1|1)=>setDraftMetrics(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});
 const savePreference=(nextMetricIds:MarketingMetricKey[],nextWidgets:MarketingDashboardWidget[],nextTable=performanceTable)=>{if(!clientId)return;const next:MarketingDashboardPreference={clientId,metricIds:nextMetricIds,widgets:nextWidgets,performanceTable:nextTable,updatedAt:new Date().toISOString()};setPreferences([next,...preferences.filter(item=>item.clientId!==clientId)])};
 const saveCustomization=()=>{if(!draftMetrics.length)return;savePreference(draftMetrics,widgets);setCustomizing(false)};
 const saveWidgets=(nextWidgets:MarketingDashboardWidget[])=>savePreference(metricIds,nextWidgets);
 const savePerformanceTable=(nextTable:MarketingPerformanceTablePreference)=>{savePreference(metricIds,widgets,nextTable);setConfiguringTable(false)};
 const applyPeriod=async()=>{
  const eligible=visibleIntegrations.filter(integration=>integration.agencyConnectionId);
  if(!eligible.length){setSyncError('As contas selecionadas precisam estar conectadas por OAuth para atualizar o período.');return}
  setSyncing(true);setSyncError('');
  try{
   const range=marketingPeriodRange(normalizeMarketingPeriodKey(periodKey));
   const results=await Promise.all(eligible.map(async integration=>({integration,result:await syncMarketingMetrics(integration.provider,{connectionId:integration.agencyConnectionId!,primaryId:integration.primaryId,resourceId:integration.resourceId,...range})})));
   let next=normalizeMarketingMetricsSnapshots(storedMetrics),updatedIntegrations=normalizeClientMarketingIntegrations(storedIntegrations);
   for(const {integration,result} of results){
    next=upsertMarketingMetricsSnapshot(next,{id:integration.id,integrationId:integration.id,clientId:integration.clientId,provider:integration.provider,periodFrom:result.period.from,periodTo:result.period.to,syncedAt:result.syncedAt,topAds:result.topAds||[],performanceRows:result.performanceRows||[],...result.metrics});
    updatedIntegrations=markMarketingIntegrationSynced(updatedIntegrations,integration.id,result.syncedAt);
   }
   setStoredMetrics(next);setStoredIntegrations(updatedIntegrations);
  }catch(error){setSyncError(error instanceof Error?error.message:'Não foi possível atualizar os dados deste período.')}finally{setSyncing(false)}
 };

 if(!integratedClients.length)return <main className="marketingDashboardPage"><section className="marketingDashboardHero"><div><span><BarChart3/> DASHBOARD DE MARKETING</span><h2>Conecte a primeira marca</h2><p>Vincule uma conta de anúncios a um cliente para começar a analisar os resultados.</p></div><Link className="btn" to="/marketing/integrations"><PlugZap/> Abrir integrações</Link></section></main>;

 return <main className="marketingDashboardPage marketingClientDashboard">
  <section className="marketingDashboardHero marketingAnalysisHero"><div><span><BarChart3/> PERFORMANCE POR CLIENTE</span><h2>{selectedClient?.companyName||'Dashboard de marketing'}</h2><p>Indicadores reais das contas vinculadas. Personalize esta visão conforme sua operação.</p></div><div className="marketingHeroControls"><label><span>Cliente</span><select aria-label="Cliente do dashboard" value={clientId} onChange={event=>setClientId(event.target.value)}>{integratedClients.map(client=><option key={client.id} value={client.id}>{client.companyName}</option>)}</select></label><button className="btn secondary" onClick={openCustomization}><Settings2/> Personalizar métricas</button></div></section>
  <section className="marketingDashboardToolbar"><div className="marketingProviderTabs" aria-label="Filtrar plataforma">{([{id:'all',label:'Todas as plataformas'},{id:'meta_ads',label:'Meta Ads'},{id:'google_ads',label:'Google Ads'}] as Array<{id:ProviderFilter;label:string}>).map(option=><button key={option.id} className={providerFilter===option.id?'active':''} disabled={option.id!=='all'&&!clientIntegrations.some(item=>item.provider===option.id)} onClick={()=>setProviderFilter(option.id)}>{option.label}</button>)}</div><div className="marketingPeriodFilter"><CalendarRange/><label><span>Período</span><select aria-label="Período do dashboard de marketing" value={normalizeMarketingPeriodKey(periodKey)} onChange={event=>setPeriodKey(event.target.value as MarketingPeriodKey)}>{marketingPeriodOptions.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><button type="button" onClick={applyPeriod} disabled={syncing}>{syncing?<RefreshCw className="spin"/>:<RefreshCw/>}{syncing?'Atualizando…':'Aplicar'}</button></div><span>Dados exibidos: {period}</span></section>
  {syncError&&<div className="marketingSyncError" role="alert">{syncError}</div>}
  <section className="marketingRealMetrics marketingSelectableMetrics" aria-label="Métricas selecionadas do cliente">{metricIds.map(id=>{const definition=marketingMetricCatalog.find(item=>item.id===id)!;return <article className="card" key={id}><small>{definition.label}</small><strong>{formatMarketingMetric(id,metricValue(metrics,id))}</strong><span>{definition.description}</span></article>})}</section>
  {!visibleSnapshots.length?<section className="card marketingNoData"><BarChart3/><h3>Este canal ainda não possui dados</h3><p>Volte às integrações e sincronize a conta de anúncios deste cliente.</p><Link className="btn" to="/marketing/integrations">Sincronizar conta</Link></section>:<>
   <div className="marketingDashboardGrid marketingPerformanceGrid"><section className="card marketingFunnelPanel"><div className="marketingPanelHead"><div><h3>Jornada de resultados</h3><p>Da entrega do anúncio até a conversão</p></div><Target/></div><div className="marketingFunnelRows"><FunnelRow label="Impressões" value={metrics.impressions} max={metrics.impressions}/><FunnelRow label="Alcance" value={metrics.reach} max={metrics.impressions}/><FunnelRow label="Cliques" value={metrics.clicks} max={metrics.impressions}/><FunnelRow label="Conversões" value={metrics.conversions} max={metrics.impressions}/></div></section><section className="card marketingEfficiencyPanel"><div className="marketingPanelHead"><div><h3>Eficiência da mídia</h3><p>Indicadores calculados com os dados sincronizados</p></div><TrendingUp/></div><div className="marketingEfficiencyGrid"><Insight icon={<MousePointerClick/>} label="CTR" value={formatMarketingMetric('ctr',metricValue(metrics,'ctr'))}/><Insight icon={<WalletCards/>} label="CPC médio" value={formatMarketingMetric('cpc',metricValue(metrics,'cpc'))}/><Insight icon={<BarChart3/>} label="CPM" value={formatMarketingMetric('cpm',metricValue(metrics,'cpm'))}/><Insight icon={<Target/>} label="Custo por conversão" value={formatMarketingMetric('costPerConversion',metricValue(metrics,'costPerConversion'))}/></div></section></div>
   <section className="card marketingChannelPanel"><div className="marketingPanelHead"><div><h3>Desempenho por canal</h3><p>Compare os canais vinculados a {selectedClient?.companyName}</p></div><Link to="/marketing/integrations">Gerenciar contas <ChevronRight/></Link></div><div className="marketingChannelTable"><div className="marketingChannelHead"><span>Canal</span><span>Investimento</span><span>Cliques</span><span>Conversões</span><span>ROAS</span><span>Atualização</span></div>{visibleSnapshots.map(snapshot=>{const integration=clientIntegrations.find(item=>item.id===snapshot.integrationId),provider=marketingProviders.find(item=>item.id===snapshot.provider);return <article key={snapshot.integrationId}><div><i className={`providerLogo ${snapshot.provider}`}>{provider?.mark}</i><span><b>{provider?.name}</b><small>{integration?.resourceName}</small></span></div><strong>{formatMarketingMetric('spend',snapshot.spend)}</strong><span>{formatMarketingMetric('clicks',snapshot.clicks)}</span><span>{formatMarketingMetric('conversions',snapshot.conversions)}</span><strong>{formatMarketingMetric('roas',snapshot.roas)}</strong><time>{dateTime(snapshot.syncedAt)}</time></article>})}</div></section>
   <section className="card marketingTopAdsPanel marketingPerformanceTablePanel"><div className="marketingPanelHead"><div><h3>Desempenho detalhado</h3><p>Compare campanhas, conjuntos de anúncios e anúncios no período</p></div><button type="button" className="marketingTableSettings" onClick={()=>setConfiguringTable(true)}><SlidersHorizontal/> Configurar tabela</button></div><div className="marketingBreakdownTabs" aria-label="Nível de detalhamento">{([{id:'campaign',label:'Campanhas'},{id:'adset',label:'Conjuntos de anúncios'},{id:'ad',label:'Anúncios'}] as Array<{id:MarketingPerformanceLevel;label:string}>).map(option=><button type="button" className={performanceTable.level===option.id?'active':''} key={option.id} onClick={()=>savePreference(metricIds,widgets,{...performanceTable,level:option.id})}>{option.label}</button>)}</div>{performanceRows.length?<PerformanceTable rows={performanceRows} metricIds={performanceTable.metricIds}/>:<div className="marketingTopAdsEmpty"><Layers3/><b>Sincronize novamente para carregar este detalhamento</b><span>A próxima sincronização da Meta Ads trará campanhas, conjuntos e anúncios.</span></div>}</section>
   <MarketingDashboardWidgets metrics={metrics} widgets={widgets} onChange={saveWidgets}/>
  </>}
  <div className="marketingDashboardActions"><Link className="btn secondary" to="/marketing/integrations"><PlugZap/> Gerenciar integrações</Link><Link className="btn" to={`/marketing/reports?client=${clientId}`}><FileText/> Criar relatório deste cliente</Link></div>
  {customizing&&<div className="overlay"><div className="modal marketingMetricsModal" role="dialog" aria-label="Personalizar métricas"><div className="modalHead"><div><small>DASHBOARD DE {selectedClient?.companyName.toUpperCase()}</small><h2>Escolher e ordenar métricas</h2><p>Selecione os indicadores e defina a ordem em que os cartões aparecem.</p></div><button className="iconBtn" onClick={()=>setCustomizing(false)}><X/></button></div><div className="marketingMetricTools"><label><Search/><input aria-label="Buscar métrica" value={metricSearch} onChange={event=>setMetricSearch(event.target.value)} placeholder="Buscar por nome ou categoria..."/></label><span><b>{draftMetrics.length}</b> selecionadas</span><button type="button" onClick={()=>setDraftMetrics(marketingMetricCatalog.map(metric=>metric.id))}>Selecionar todas</button></div><section className="marketingMetricOrder"><header><div><b>Ordem dos cartões</b><small>Use as setas para reorganizar o dashboard</small></div></header><div>{draftMetrics.map((id,index)=>{const metric=marketingMetricCatalog.find(item=>item.id===id);return <article key={id}><GripVertical/><span><b>{index+1}. {metric?.label}</b><small>{metric?.category}</small></span><button type="button" aria-label={`Mover ${metric?.label} para cima`} onClick={()=>moveDraftMetric(index,-1)} disabled={!index}><ArrowUp/></button><button type="button" aria-label={`Mover ${metric?.label} para baixo`} onClick={()=>moveDraftMetric(index,1)} disabled={index===draftMetrics.length-1}><ArrowDown/></button></article>})}</div></section><div className="marketingMetricChoices">{metricCategories.map(category=>{const items=filteredMetricCatalog.filter(metric=>metric.category===category);return items.length?<section key={category}><header><b>{category}</b><small>{items.length} métricas</small></header><div>{items.map(metric=><label className={draftMetrics.includes(metric.id)?'selected':''} key={metric.id}><input type="checkbox" checked={draftMetrics.includes(metric.id)} onChange={()=>toggleMetric(metric.id)}/><span><b>{metric.label}</b><small>{metric.description}</small></span></label>)}</div></section>:null})}{!filteredMetricCatalog.length&&<div className="marketingMetricEmpty">Nenhuma métrica encontrada para “{metricSearch}”.</div>}</div><div className="formActions"><button className="btn secondary" onClick={()=>setDraftMetrics([...defaultMarketingMetricIds])}>Restaurar padrão</button><button className="btn" disabled={!draftMetrics.length} onClick={saveCustomization}>Salvar dashboard</button></div></div></div>}
  {configuringTable&&<PerformanceTableModal initial={performanceTable} onClose={()=>setConfiguringTable(false)} onSave={savePerformanceTable}/>}
 </main>;
}

function FunnelRow({label,value,max}:{label:string;value:number;max:number}){const percentage=max?Math.max(2,value/max*100):0;return <div><span><b>{label}</b><strong>{Math.round(value).toLocaleString('pt-BR')}</strong></span><i><em style={{width:`${Math.min(100,percentage)}%`}}/></i></div>}
function Insight({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>}
function PerformanceTable({rows,metricIds}:{rows:Array<MarketingPerformanceRow&{key:string}>;metricIds:MarketingMetricKey[]}){const columns=`minmax(240px,1.8fr) repeat(${metricIds.length},minmax(105px,.8fr))`;return <div className="marketingTopAdsTable marketingPerformanceTable"><div className="marketingTopAdsHead" style={{gridTemplateColumns:columns}}><span>Nome</span>{metricIds.map(id=><span key={id}>{marketingMetricCatalog.find(metric=>metric.id===id)?.label}</span>)}</div>{rows.map((row,index)=><article key={row.key} style={{gridTemplateColumns:columns}}><div><i>{index+1}</i><span><b>{row.name}</b><small>{performanceContext(row)}</small></span></div>{metricIds.map(id=><span key={id}>{formatMarketingMetric(id,metricValue(row,id))}</span>)}</article>)}</div>}
function performanceContext(row:MarketingPerformanceRow){if(row.level==='campaign')return 'Campanha';if(row.level==='adset')return row.campaignName||'Campanha não informada';return [row.campaignName,row.adSetName].filter(Boolean).join(' · ')||'Origem não informada'}
function PerformanceTableModal({initial,onClose,onSave}:{initial:MarketingPerformanceTablePreference;onClose:()=>void;onSave:(value:MarketingPerformanceTablePreference)=>void}){const [level,setLevel]=useState(initial.level),[selected,setSelected]=useState([...initial.metricIds]),[search,setSearch]=useState('');const query=search.trim().toLocaleLowerCase('pt-BR'),visible=marketingMetricCatalog.filter(metric=>!query||`${metric.label} ${metric.category}`.toLocaleLowerCase('pt-BR').includes(query));const toggle=(id:MarketingMetricKey)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):current.length<6?[...current,id]:current);return <div className="overlay"><div className="modal marketingWidgetModal marketingTableModal" role="dialog" aria-label="Configurar tabela de desempenho"><div className="modalHead"><div><small>DETALHAMENTO DA MÍDIA</small><h2>Configurar tabela</h2><p>Escolha o nível de análise e até seis colunas de métricas.</p></div><button type="button" className="iconBtn" aria-label="Fechar" onClick={onClose}><X/></button></div><form onSubmit={event=>{event.preventDefault();if(selected.length)onSave({level,metricIds:selected})}}><fieldset className="marketingWidgetTypes"><legend>Mostrar dados por</legend><div>{([{id:'campaign',label:'Campanhas'},{id:'adset',label:'Conjuntos'},{id:'ad',label:'Anúncios'}] as Array<{id:MarketingPerformanceLevel;label:string}>).map(option=><label className={level===option.id?'selected':''} key={option.id}><input type="radio" checked={level===option.id} onChange={()=>setLevel(option.id)}/><span><Layers3/></span><b>{option.label}</b><small>Nível da conta de anúncios</small></label>)}</div></fieldset><div className="marketingWidgetMetricHead"><div><b>Colunas da tabela</b><small>{selected.length}/6 selecionadas</small></div><label><Search/><input aria-label="Buscar coluna da tabela" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar métrica..."/></label></div><div className="marketingWidgetMetrics">{visible.map(metric=><label className={selected.includes(metric.id)?'selected':''} key={metric.id}><input type="checkbox" checked={selected.includes(metric.id)} onChange={()=>toggle(metric.id)}/><span><b>{metric.label}</b><small>{metric.category}</small></span></label>)}</div><div className="formActions"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn" disabled={!selected.length}>Salvar tabela</button></div></form></div></div>}
const date=(value?:string)=>value?new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—';
const dateTime=(value?:string)=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
