import type {AgencyService,ServiceCapability} from './ServicesManager';

export type ServiceLinkedRecord={serviceIds?:string[];services?:string[]};
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const slug=(value:string)=>normalize(value).replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')||'servico';

export function ensureLegacyServices(catalog:AgencyService[],records:ServiceLinkedRecord[]){const next=[...catalog];for(const reference of records.flatMap(record=>record.serviceIds?.length?record.serviceIds:record.services||[])){if(next.some(service=>service.id===reference||normalize(service.name)===normalize(reference)))continue;let id=`legacy-${slug(reference)}`,suffix=2;while(next.some(service=>service.id===id))id=`legacy-${slug(reference)}-${suffix++}`;next.push({id,name:reference,description:'Serviço preservado durante a migração dos vínculos existentes.',price:0,pricingType:'variable',capabilities:normalize(reference)==='social media'?['editorial']:[],active:true,createdAt:new Date().toISOString()})}return next}
export const hasEditorialCapability=(service:AgencyService|undefined)=>Boolean(service?.capabilities?.includes('editorial'));
export function migrateServiceCapabilities(catalog:AgencyService[]):AgencyService[]{return catalog.map(service=>{if(hasEditorialCapability(service))return service;const wasSocialMedia=service.id==='social'||normalize(service.name)==='social media';return wasSocialMedia?{...service,capabilities:['editorial'] as ServiceCapability[]}:service})}
export function resolveServiceIds(record:ServiceLinkedRecord|undefined,catalog:AgencyService[]){const references=record?.serviceIds?.length?record.serviceIds:record?.services||[];return Array.from(new Set(references.map(reference=>catalog.find(service=>service.id===reference||normalize(service.name)===normalize(reference))?.id).filter((id):id is string=>Boolean(id))))}
export function linkedServices(record:ServiceLinkedRecord|undefined,catalog:AgencyService[]){return resolveServiceIds(record,catalog).map(id=>catalog.find(service=>service.id===id)).filter((service):service is AgencyService=>Boolean(service))}
export function migrateServiceRecords<T extends ServiceLinkedRecord>(records:T[],catalog:AgencyService[]){return records.map(record=>{const {services:legacyServices,...rest}=record;return {...rest,serviceIds:resolveServiceIds(record,catalog)} as T})}
