import {useEffect,useState} from 'react';
import {Download,RotateCcw,Save,Upload} from 'lucide-react';
import {notificationSoundEnabled,notificationSoundKey,playNotificationSound} from './notification-sound';
import {getNotificationPreferences,notificationPreferenceOptions,setNotificationPreferences} from './notification-preferences';
import {store} from './storage';
import ServicesManager from './ServicesManager';

type GeneralSettings={agencyName:string;email:string;phone:string;website:string;currency:string;timezone:string};
type AgencyProfile={legalName:string;taxId:string;address:string};
const generalDefaults:GeneralSettings={agencyName:'Agência ROAS',email:'contato@agenciaroas.com.br',phone:'(11) 99999-0000',website:'www.agenciaroas.com.br',currency:'BRL — Real brasileiro',timezone:'America/Sao_Paulo'};
const agencyDefaults:AgencyProfile={legalName:'Agência ROAS Ltda.',taxId:'',address:''};
const loadGeneralSettings=()=>{
  const legacy=store.get<Partial<GeneralSettings&AgencyProfile>>('agency_settings',{});
  const saved=store.get<Partial<GeneralSettings>>('general_settings',{});
  return {...generalDefaults,...legacy,...saved};
};
const loadAgencyProfile=()=>{
  const legacy=store.get<Partial<GeneralSettings&AgencyProfile>>('agency_settings',{});
  const saved=store.get<Partial<AgencyProfile>>('agency_profile',{});
  return {...agencyDefaults,...legacy,...saved};
};

const tabs=['Geral','Agência','Serviços','Aparência','Notificações','Dados','Backup'];
export default function SettingsPage(){
  const [tab,setTab]=useState('Geral');
  const [theme,setTheme]=useState(localStorage.getItem('roas_theme')||'light');
  const [sidebarOpen,setSidebarOpen]=useState(localStorage.getItem('roas_sidebar_open')!=='false');
  const [soundEnabled,setSoundEnabled]=useState(notificationSoundEnabled);
  const [notificationPreferences,setNotificationPreferenceState]=useState(getNotificationPreferences);
  const [generalSettings,setGeneralSettings]=useState<GeneralSettings>(loadGeneralSettings);
  const [agencyProfile,setAgencyProfile]=useState<AgencyProfile>(loadAgencyProfile);
  const [saved,setSaved]=useState<'general'|'agency'|null>(null);
  useEffect(()=>{const apply=(value:string)=>{const resolved=value==='system'?(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;document.documentElement.dataset.theme=resolved};apply(theme);const media=window.matchMedia('(prefers-color-scheme: dark)');const listener=()=>theme==='system'&&apply(theme);media.addEventListener('change',listener);return()=>media.removeEventListener('change',listener)},[theme]);
  const showSaved=(section:'general'|'agency')=>{setSaved(section);setTimeout(()=>setSaved(current=>current===section?null:current),2200)};
  const saveGeneral=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();store.set('general_settings',generalSettings);showSaved('general')};
  const saveAgency=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();store.set('agency_profile',agencyProfile);showSaved('agency')};
  const download=()=>{const values=Object.fromEntries(Object.entries(localStorage).filter(([key])=>key.startsWith('roas_')));const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(values,null,2)],{type:'application/json'}));link.download='backup-roas.json';link.click();URL.revokeObjectURL(link.href)};
  const importBackup=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());const entries=Object.entries(parsed).filter(([key,value])=>key.startsWith('roas_')&&typeof value==='string');if(!entries.length)throw new Error('invalid');if(!confirm(`Importar ${entries.length} conjuntos de dados deste backup?`))return;entries.forEach(([key,value])=>localStorage.setItem(key,String(value)));location.reload()}catch{alert('Este arquivo não é um backup válido do sistema ROAS.')}finally{event.target.value=''}};
  return <main><section className="card settings"><div className="settingsNav">{tabs.map(label=><button key={label} className={tab===label?'active':''} onClick={()=>setTab(label)}>{label}</button>)}</div><div className="settingsBody">
    {tab==='Geral'&&<><h2>Configurações gerais</h2><p>Escolha como sua operação será apresentada no sistema.</p><form className="form" onSubmit={saveGeneral}><label>Nome da agência<input name="agencyName" value={generalSettings.agencyName} onChange={event=>setGeneralSettings(current=>({...current,agencyName:event.target.value}))}/></label><label>E-mail<input name="email" type="email" value={generalSettings.email} onChange={event=>setGeneralSettings(current=>({...current,email:event.target.value}))}/></label><label>Telefone<input name="phone" value={generalSettings.phone} onChange={event=>setGeneralSettings(current=>({...current,phone:event.target.value}))}/></label><label>Site<input name="website" value={generalSettings.website} onChange={event=>setGeneralSettings(current=>({...current,website:event.target.value}))}/></label><label>Moeda<select name="currency" value={generalSettings.currency} onChange={event=>setGeneralSettings(current=>({...current,currency:event.target.value}))}><option>BRL — Real brasileiro</option><option>USD — Dólar americano</option></select></label><label>Fuso horário<select name="timezone" value={generalSettings.timezone} onChange={event=>setGeneralSettings(current=>({...current,timezone:event.target.value}))}><option>America/Sao_Paulo</option><option>UTC</option></select></label><div className="formActions full"><button className="btn"><Save/> Salvar alterações</button></div></form>{saved==='general'&&<div className="inlineSuccess">✓ Configurações gerais salvas neste navegador.</div>}</>}
    {tab==='Agência'&&<><h2>Perfil da agência</h2><p>Informações institucionais exibidas em relatórios e documentos.</p><form className="form" onSubmit={saveAgency}><label>Razão social<input name="legalName" value={agencyProfile.legalName} onChange={event=>setAgencyProfile(current=>({...current,legalName:event.target.value}))}/></label><label>CNPJ<input name="taxId" value={agencyProfile.taxId} onChange={event=>setAgencyProfile(current=>({...current,taxId:event.target.value}))} placeholder="00.000.000/0001-00"/></label><label className="full">Endereço<input name="address" value={agencyProfile.address} onChange={event=>setAgencyProfile(current=>({...current,address:event.target.value}))} placeholder="Rua, número, cidade e estado"/></label><div className="formActions full"><button className="btn"><Save/> Salvar perfil</button></div></form>{saved==='agency'&&<div className="inlineSuccess">✓ Perfil da agência salvo neste navegador.</div>}</>}
    {tab==='Serviços'&&<ServicesManager/>}
    {tab==='Aparência'&&<><h2>Aparência</h2><p>Defina a preferência visual do sistema.</p><div className="themeChoices">{['light','dark','system'].map(value=><button key={value} className={theme===value?'active':''} onClick={()=>{setTheme(value);localStorage.setItem('roas_theme',value)}}>{value==='light'?'☀️ Tema claro':value==='dark'?'🌙 Tema escuro':'💻 Sistema'}</button>)}</div><p className="settingsHint">A mudança é aplicada imediatamente e fica salva neste navegador.</p><hr/><h2>Menu lateral</h2><p>Escolha como o menu deve aparecer ao acessar o sistema.</p><div className="sidebarPreference"><div><b>Menu expandido</b><span>Exibe os ícones e os nomes de todas as páginas.</span></div><button type="button" role="switch" aria-checked={sidebarOpen} className={'switchControl '+(sidebarOpen?'on':'')} onClick={()=>{const next=!sidebarOpen;setSidebarOpen(next);localStorage.setItem('roas_sidebar_open',String(next));window.dispatchEvent(new CustomEvent('roas-sidebar-toggle',{detail:next}))}}><i/></button></div><div className="sidebarPreview"><div className={sidebarOpen?'previewMenu open':'previewMenu'}><span>R</span>{sidebarOpen&&<><b>Dashboard</b><b>Clientes</b><b>Projetos</b></>}</div><p>{sidebarOpen?'O menu ficará aberto por padrão.':'O menu ficará recolhido, mostrando apenas os ícones.'}</p></div></>}
    {tab==='Notificações'&&<><h2>Notificações</h2><p>Escolha os alertas que deseja acompanhar.</p><div className="toggleList"><label className="soundNotificationSetting"><span><b>Avisos sonoros</b><small>Reproduzir um som para novas notificações e conversões de leads no CRM.</small></span><input type="checkbox" checked={soundEnabled} onChange={event=>{const enabled=event.target.checked;localStorage.setItem(notificationSoundKey,String(enabled));setSoundEnabled(enabled);if(enabled)playNotificationSound('notification')}}/></label>{notificationPreferenceOptions.map(option=><label key={option.key}><span><b>{option.label}</b><small>{option.description}</small></span><input type="checkbox" checked={notificationPreferences[option.key]} onChange={event=>{const next={...notificationPreferences,[option.key]:event.target.checked};setNotificationPreferenceState(next);setNotificationPreferences(next)}}/></label>)}</div><p className="settingsHint">As preferências são aplicadas imediatamente e ficam salvas neste navegador. Ao ativar o som, um aviso de teste será reproduzido.</p></>}
    {tab==='Dados'&&<><h2>Dados locais</h2><p>Exporte, importe ou restaure os dados armazenados neste navegador.</p><div className="dangerRow"><button className="btn secondary" onClick={download}><Download/> Exportar backup</button><label className="btn secondary importBackup"><Upload/> Importar backup<input type="file" accept="application/json,.json" onChange={importBackup}/></label><button className="btn secondary" onClick={()=>{if(confirm('Restaurar todos os dados demonstrativos?')){store.reset();location.reload()}}}><RotateCcw/> Restaurar demonstração</button></div><p className="dataSafety">A importação aceita apenas arquivos JSON exportados pelo próprio sistema.</p></>}
    {tab==='Backup'&&<><h2>Backup</h2><p>O sistema salva automaticamente no navegador deste dispositivo.</p><div className="backupBox"><b>Backup local ativo</b><span>Dados protegidos no localStorage do navegador.</span><button className="btn" onClick={download}><Download/> Baixar backup agora</button></div></>}
  </div></section></main>
}
