import {useRef,useState} from 'react';
import {Bold,ExternalLink,FileText,ImagePlus,Italic,Link2,LoaderCircle,Paperclip,Strikethrough,Trash2} from 'lucide-react';
import {openClientFile,uploadClientFile} from './client-files';
import {parseTaskDescription,validTaskLink,wrapDescriptionSelection} from './task-description';
import type {TaskAttachment} from './types';

export function FormattedTaskDescription({value,className=''}:{value?:string;className?:string}){
 if(!value?.trim())return null;
 return <div className={`formattedTaskDescription ${className}`}>{parseTaskDescription(value).map((token,index)=>token.type==='bold'?<strong key={index}>{token.value}</strong>:token.type==='italic'?<em key={index}>{token.value}</em>:token.type==='strike'?<s key={index}>{token.value}</s>:<span key={index}>{token.value}</span>)}</div>
}

export default function TaskDescriptionEditor({defaultValue='',clientId,attachments,onAttachmentsChange,onUploaded}:{defaultValue?:string;clientId:string;attachments:TaskAttachment[];onAttachmentsChange:(items:TaskAttachment[])=>void;onUploaded?:(fileId:string)=>void}){
 const [value,setValue]=useState(defaultValue),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[showLink,setShowLink]=useState(false),[link,setLink]=useState(''),[linkName,setLinkName]=useState('');
 const textarea=useRef<HTMLTextAreaElement>(null),fileInput=useRef<HTMLInputElement>(null),mediaInput=useRef<HTMLInputElement>(null);
 const format=(marker:string)=>{const element=textarea.current;if(!element)return;const next=wrapDescriptionSelection(value,element.selectionStart,element.selectionEnd,marker);setValue(next.value);requestAnimationFrame(()=>{element.focus();element.setSelectionRange(next.selectionStart,next.selectionEnd)})};
 const upload=async(file?:File)=>{if(!file)return;if(!clientId){setError('Selecione um cliente antes de anexar arquivos.');return}setUploading(true);setError('');try{const result=await uploadClientFile(clientId,file),type:TaskAttachment['type']=file.type.startsWith('image/')||file.type.startsWith('video/')||file.type.startsWith('audio/')?'media':'file';onAttachmentsChange([...attachments,{id:crypto.randomUUID(),type,name:result.name,fileId:result.fileId,mimeType:result.mimeType,size:result.size,createdAt:new Date().toISOString()}]);onUploaded?.(result.fileId)}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível anexar o arquivo.')}finally{setUploading(false);if(fileInput.current)fileInput.current.value='';if(mediaInput.current)mediaInput.current.value=''}};
 const addLink=()=>{const normalized=/^https?:\/\//i.test(link.trim())?link.trim():`https://${link.trim()}`;if(!validTaskLink(normalized)){setError('Informe um link válido, como https://exemplo.com.');return}onAttachmentsChange([...attachments,{id:crypto.randomUUID(),type:'link',name:linkName.trim()||normalized,url:normalized,createdAt:new Date().toISOString()}]);setLink('');setLinkName('');setShowLink(false);setError('')};
 const remove=(attachment:TaskAttachment)=>onAttachmentsChange(attachments.filter(item=>item.id!==attachment.id));
 return <div className="taskDescriptionEditor full"><label>Descrição</label><div className="taskDescriptionBox"><div className="taskDescriptionToolbar"><button type="button" title="Negrito" onClick={()=>format('**')}><Bold/></button><button type="button" title="Itálico" onClick={()=>format('_')}><Italic/></button><button type="button" title="Tachado" onClick={()=>format('~~')}><Strikethrough/></button><i/><button type="button" title="Adicionar arquivo" disabled={uploading} onClick={()=>fileInput.current?.click()}><Paperclip/></button><button type="button" title="Adicionar mídia" disabled={uploading} onClick={()=>mediaInput.current?.click()}><ImagePlus/></button><button type="button" title="Adicionar link" onClick={()=>setShowLink(current=>!current)}><Link2/></button>{uploading&&<span><LoaderCircle className="spin"/> Enviando...</span>}</div><textarea ref={textarea} name="description" value={value} onChange={event=>setValue(event.target.value)} placeholder="Contexto, briefing ou instruções importantes"/><input ref={fileInput} hidden type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt" onChange={event=>void upload(event.target.files?.[0])}/><input ref={mediaInput} hidden type="file" accept="image/jpeg,image/png,image/webp,video/mp4,audio/mpeg,audio/mp4" onChange={event=>void upload(event.target.files?.[0])}/></div><small className="taskEditorHint">Selecione um trecho e use a barra para formatar. Arquivos e mídias: até 4 MB.</small>{showLink&&<div className="taskLinkForm"><input value={linkName} onChange={event=>setLinkName(event.target.value)} placeholder="Nome do link (opcional)"/><input value={link} onChange={event=>setLink(event.target.value)} placeholder="https://..."/><button type="button" className="btn" onClick={addLink}>Adicionar</button></div>}{error&&<p className="taskAttachmentError">{error}</p>}{attachments.length>0&&<div className="taskAttachments">{attachments.map(attachment=><article key={attachment.id}><span>{attachment.type==='media'?<ImagePlus/>:attachment.type==='link'?<Link2/>:<FileText/>}</span><div><b>{attachment.name}</b><small>{attachment.type==='link'?'Link externo':attachment.size?`${(attachment.size/1024/1024).toFixed(1)} MB`:'Arquivo'}</small></div>{attachment.type==='link'?<a href={attachment.url} target="_blank" rel="noreferrer" title="Abrir link"><ExternalLink/></a>:<button type="button" title="Abrir arquivo" onClick={()=>attachment.fileId&&void openClientFile(attachment.fileId)}><ExternalLink/></button>}<button type="button" className="remove" title="Remover" onClick={()=>void remove(attachment)}><Trash2/></button></article>)}</div>}{value.trim()&&<div className="taskDescriptionPreview"><small>Pré-visualização</small><FormattedTaskDescription value={value}/></div>}</div>
}
