import {useState} from 'react';
import {CircleCheck,Clock3,DollarSign,FolderKanban,Layers,Plus,Trash2} from 'lucide-react';
import type {Client,GenericItem} from '../types';
import {pageMeta} from '../app/navigation';
import {useStoreData} from '../app/useStoreData';
import {Badge,Button,Empty,Filter,Modal,money} from '../components/ui';

export default function GenericPage({type}:{type:string}){
 const meta=pageMeta[type]||{title:'Registros',sub:''},[data,setData]=useStoreData<GenericItem[]>(type,[]),[clients]=useStoreData<Client[]>('clients',[]);
 const [query,setQuery]=useState(''),[modal,setModal]=useState(false),[selected,setSelected]=useState<GenericItem|null>(null),filtered=data.filter(item=>item.name.toLowerCase().includes(query.toLowerCase()));
 const save=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),now=new Date().toISOString(),item:GenericItem={id:selected?.id||crypto.randomUUID(),name:String(form.get('name')),clientId:String(form.get('client')),status:String(form.get('status')),value:Number(form.get('value')||0),date:String(form.get('date')),description:String(form.get('description')),category:String(form.get('category')),createdAt:selected?.createdAt||now,updatedAt:now};setData(selected?data.map(current=>current.id===item.id?item:current):[item,...data]);setModal(false);setSelected(null)};
 return <main><div className="stats genericStats"><GenericStat title={`Total de ${meta.title.toLowerCase()}`} value={String(data.length)} icon={<Layers/>}/><GenericStat title="Ativos" value={String(data.filter(item=>/ativ|conect|confirm/i.test(item.status)).length)} icon={<CircleCheck/>} tone="blue"/><GenericStat title="Pendentes" value={String(data.filter(item=>/pend|dispon/i.test(item.status)).length)} icon={<Clock3/>} tone="orange"/><GenericStat title="Valor total" value={money(data.reduce((sum,item)=>sum+(item.value||0),0))} icon={<DollarSign/>} tone="green"/></div><section className="card genericPanel"><div className="panelTop"><Filter query={query} setQuery={setQuery} placeholder={`Buscar ${meta.title.toLowerCase()}...`}/><Button onClick={()=>{setSelected(null);setModal(true)}}><Plus/> Novo registro</Button></div><div className="genericGrid">{filtered.map(item=><article key={item.id} className="itemCard" onClick={()=>{setSelected(item);setModal(true)}}><div className="itemIcon"><FolderKanban/></div><div><h3>{item.name}</h3><p>{item.description}</p><span>{clients.find(client=>client.id===item.clientId)?.companyName||item.category}</span></div><Badge tone={/pend|paus|dispon/i.test(item.status)?'orange':'green'}>{item.status}</Badge><strong>{item.value?money(item.value):''}</strong><button className="iconBtn" onClick={event=>{event.stopPropagation();if(confirm('Excluir registro?'))setData(data.filter(current=>current.id!==item.id))}}><Trash2/></button></article>)}</div>{!filtered.length&&<Empty label="registro"/>}</section>{modal&&<Modal title={selected?'Editar registro':`Novo em ${meta.title}`} onClose={()=>{setModal(false);setSelected(null)}}><form onSubmit={save} className="form"><label className="full">Nome<input name="name" required defaultValue={selected?.name}/></label><label>Cliente<select name="client" defaultValue={selected?.clientId}><option value="">Sem cliente</option>{clients.map(client=><option key={client.id} value={client.id}>{client.companyName}</option>)}</select></label><label>Status<input name="status" defaultValue={selected?.status||'Ativo'}/></label><label>Valor<input name="value" type="number" defaultValue={selected?.value}/></label><label>Data<input name="date" type="date" defaultValue={selected?.date}/></label><label>Categoria<input name="category" defaultValue={selected?.category}/></label><label className="full">Descrição<textarea name="description" defaultValue={selected?.description}/></label><div className="formActions full"><Button secondary onClick={()=>setModal(false)}>Cancelar</Button><Button type="submit">Salvar</Button></div></form></Modal>}</main>
}

function GenericStat({title,value,icon,tone='' }:{title:string;value:string;icon:React.ReactNode;tone?:string}){return <article className="stat card"><div className={`statIcon ${tone}`}>{icon}</div><div><small>{title}</small><strong>{value}</strong></div><p><b>Atualizado</b> agora</p></article>}
