import {useState} from 'react';
import {CheckCircle2,UsersRound,X} from 'lucide-react';
import {store} from './storage';
import type {Client,Project,Task,TeamMember} from './types';

export default function ClientTaskModal({client,onClose}:{client:Client;onClose:()=>void}){
 const [projects]=useState<Project[]>(()=>store.get<Project[]>('projects',[]).filter(project=>project.clientId===client.id)),[team]=useState<TeamMember[]>(()=>store.get('team',[])),[saved,setSaved]=useState(false);
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),all=store.get<Task[]>('tasks',[]),responsibleIds=form.getAll('responsibleIds').map(String),now=new Date().toISOString(),task:Task={id:crypto.randomUUID(),title:String(form.get('title')),description:String(form.get('description')),clientId:client.id,projectId:String(form.get('project')||''),responsibleId:responsibleIds[0]||'',responsibleIds,status:String(form.get('status')) as Task['status'],priority:String(form.get('priority')) as Task['priority'],dueDate:String(form.get('dueDate')),tags:String(form.get('tags')||'').split(',').map(tag=>tag.trim()).filter(Boolean),position:all.length,commentsCount:0,attachmentsCount:0,createdAt:now,updatedAt:now};store.set('tasks',[task,...all]);const activities=store.get<{id:string;type:string;description:string;clientId:string;createdAt:string}[]>('activities',[]);store.set('activities',[{id:crypto.randomUUID(),type:'task',description:`Nova tarefa criada: ${task.title}`,clientId:client.id,createdAt:now},...activities]);setSaved(true);setTimeout(onClose,900)};
 return <div className="overlay"><div className="modal clientTaskModal"><div className="modalHead"><div><small>NOVA TAREFA PARA</small><h2>{client.companyName}</h2><p>{client.contactName} · {client.instagram}</p></div><button className="iconBtn" onClick={onClose}><X/></button></div>{saved?<div className="taskSaved"><CheckCircle2/><b>Tarefa criada com sucesso</b><span>Ela já está disponível no painel de Tarefas.</span></div>:<form className="form" onSubmit={submit}><label className="full">Título da tarefa<input name="title" required autoFocus placeholder="Ex.: Revisar campanha de captação"/></label><label className="full">Descrição<textarea name="description" placeholder="Contexto, briefing ou instruções importantes"/></label><label>Projeto<select name="project"><option value="">Sem projeto específico</option>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Status<select name="status" defaultValue="todo"><option value="todo">A fazer</option><option value="pending">Pendente</option><option value="in_progress">Em andamento</option></select></label><div className="full taskResponsiblesField"><b><UsersRound/> Pessoas responsáveis</b><small>Selecione uma ou mais pessoas para executar esta tarefa.</small><div className="taskResponsiblesGrid">{team.filter(member=>member.status==='active').map(member=><label key={member.id}><input name="responsibleIds" type="checkbox" value={member.id}/><span className="multiTaskAvatar" style={{background:member.color}}>{member.name.split(' ').slice(0,2).map(part=>part[0]).join('')}</span><span><b>{member.name}</b><small>{member.roles?.join(', ')||member.role}</small></span></label>)}</div></div><label>Prioridade<select name="priority" defaultValue="medium"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Prazo<input name="dueDate" type="date" required/></label><label className="full">Etiquetas<input name="tags" placeholder="Ex.: campanha, urgente"/></label><div className="clientTaskInfo full"><b>Cliente vinculado</b><span>{client.companyName}</span><small>Essa tarefa ficará associada automaticamente a este cliente.</small></div><div className="formActions full"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn">Criar tarefa</button></div></form>}</div></div>
}
