import {useState} from 'react';
import {CheckCircle2, X} from 'lucide-react';
import {store} from './storage';
import type {Client, Project, Task, TeamMember} from './types';

export default function ClientTaskModal({client,onClose}:{client:Client;onClose:()=>void}){
 const [projects]=useState<Project[]>(()=>store.get('projects',[]).filter((p:Project)=>p.clientId===client.id));
 const [team]=useState<TeamMember[]>(()=>store.get('team',[]));
 const [saved,setSaved]=useState(false);
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const all=store.get<Task[]>('tasks',[]);const task:Task={id:crypto.randomUUID(),title:String(f.get('title')),description:String(f.get('description')),clientId:client.id,projectId:String(f.get('project')||''),responsibleId:String(f.get('responsible')||''),status:String(f.get('status')) as Task['status'],priority:String(f.get('priority')) as Task['priority'],dueDate:String(f.get('dueDate')),tags:String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),position:all.length,commentsCount:0,attachmentsCount:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};store.set('tasks',[task,...all]);const activities=store.get<any[]>('activities',[]);store.set('activities',[{id:crypto.randomUUID(),type:'task',description:`Nova tarefa criada: ${task.title}`,clientId:client.id,createdAt:new Date().toISOString()},...activities]);setSaved(true);setTimeout(onClose,900)};
 return <div className="overlay"><div className="modal clientTaskModal"><div className="modalHead"><div><small>NOVA TAREFA PARA</small><h2>{client.companyName}</h2><p>{client.contactName} · {client.instagram}</p></div><button className="iconBtn" onClick={onClose}><X/></button></div>{saved?<div className="taskSaved"><CheckCircle2/><b>Tarefa criada com sucesso</b><span>Ela já está disponível no painel de Tarefas.</span></div>:<form className="form" onSubmit={submit}><label className="full">Título da tarefa<input name="title" required autoFocus placeholder="Ex.: Revisar campanha de captação"/></label><label className="full">Descrição<textarea name="description" placeholder="Contexto, briefing ou instruções importantes"/></label><label>Projeto<select name="project"><option value="">Sem projeto específico</option>{projects.map(project=><option value={project.id}>{project.name}</option>)}</select></label><label>Responsável<select name="responsible"><option value="">Definir depois</option>{team.map(member=><option value={member.id}>{member.name}</option>)}</select></label><label>Status<select name="status" defaultValue="todo"><option value="todo">A fazer</option><option value="pending">Pendente</option><option value="in_progress">Em andamento</option></select></label><label>Prioridade<select name="priority" defaultValue="medium"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Prazo<input name="dueDate" type="date" required/></label><label>Etiquetas<input name="tags" placeholder="Ex.: campanha, urgente"/></label><div className="clientTaskInfo full"><b>Cliente vinculado</b><span>{client.companyName}</span><small>Essa tarefa ficará associada automaticamente a este cliente.</small></div><div className="formActions full"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn">Criar tarefa</button></div></form>}</div></div>
}
