import {useMemo,useState} from 'react';
import {ArrowLeft,CalendarDays,ChevronLeft,ChevronRight,ExternalLink,GripVertical,LayoutGrid,List,Palette,Pencil,Plus,Trash2,X} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {useStoreData} from './app/useStoreData';
import type {Project} from './types';
import './editorial.css';

type EditorialStatus='todo'|'in_progress'|'completed';
type EditorialFormat='Reels'|'Post estático'|'Carrossel';
type WorkflowKey='planning'|'creative'|'copy'|'approval'|'scheduling'|'completed';
type Workflow=Record<WorkflowKey,boolean>;
type EditorialPost={id:string;date:string;name:string;headline:string;format:EditorialFormat;reference:string;steps:Workflow;createdAt:string;updatedAt:string};

const workflow:[WorkflowKey,string][]=[['planning','Planejamento'],['creative','Criativo'],['copy','Copy'],['approval','Aprovação'],['scheduling','Programar'],['completed','Concluído']];
const emptySteps=():Workflow=>({planning:false,creative:false,copy:false,approval:false,scheduling:false,completed:false});
const statusOf=(post:EditorialPost):EditorialStatus=>post.steps.completed?'completed':Object.values(post.steps).some(Boolean)?'in_progress':'todo';
const statusLabel:Record<EditorialStatus,string>={todo:'A fazer',in_progress:'Em andamento',completed:'Concluído'};
const statusTone:Record<EditorialStatus,string>={todo:'purple',in_progress:'orange',completed:'green'};
const formatDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR');
const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const initials=(name:string)=>name.split(' ').slice(0,2).map(part=>part[0]).join('').toUpperCase();

export default function EditorialPage(){
 const {projectId=''}=useParams(),[projects]=useStoreData<Project[]>('projects',[]),project=projects.find(item=>item.id===projectId);
 const [posts,setPosts]=useStoreData<EditorialPost[]>(`editorial_${projectId}`,[]),[modal,setModal]=useState(false),[editing,setEditing]=useState<EditorialPost|null>(null),[dragged,setDragged]=useState<string|null>(null),[calendarDate,setCalendarDate]=useState(()=>new Date());
 const columns:EditorialStatus[]=['todo','in_progress','completed'];
 const stats=useMemo(()=>({total:posts.length,todo:posts.filter(post=>statusOf(post)==='todo').length,progress:posts.filter(post=>statusOf(post)==='in_progress').length,completed:posts.filter(post=>statusOf(post)==='completed').length}),[posts]);
 if(!project)return <main className="editorialPage"><div className="editorialMissing"><Palette/><h2>Projeto não encontrado</h2><Link className="btn" to="/projects">Voltar para Projetos</Link></div></main>;

 const savePost=(post:EditorialPost)=>{setPosts(editing?posts.map(item=>item.id===post.id?post:item):[post,...posts]);setEditing(null);setModal(false)};
 const remove=(post:EditorialPost)=>{if(confirm(`Excluir o conteúdo “${post.name}”?`))setPosts(posts.filter(item=>item.id!==post.id))};
 const toggleStep=(post:EditorialPost,key:WorkflowKey,checked:boolean)=>{let steps={...post.steps,[key]:checked};if(key==='completed'&&checked)steps=Object.fromEntries(workflow.map(([step])=>[step,true])) as Workflow;if(key!=='completed'&&!checked)steps.completed=false;setPosts(posts.map(item=>item.id===post.id?{...item,steps,updatedAt:new Date().toISOString()}:item))};
 const movePost=(status:EditorialStatus)=>{if(!dragged)return;setPosts(posts.map(post=>{if(post.id!==dragged)return post;let steps=post.steps;if(status==='todo')steps=emptySteps();if(status==='in_progress')steps={...post.steps,planning:true,completed:false};if(status==='completed')steps=Object.fromEntries(workflow.map(([key])=>[key,true])) as Workflow;return{...post,steps,updatedAt:new Date().toISOString()}}));setDragged(null)};
 return <main className="editorialPage">
  <div className="editorialHero"><div><Link to="/projects"><ArrowLeft/> Projetos</Link><small>LINHA EDITORIAL</small><h2>{project.name}</h2><p>Planeje, produza, aprove e programe os conteúdos do projeto.</p></div><button className="btn" onClick={()=>{setEditing(null);setModal(true)}}><Plus/> Novo conteúdo</button></div>
  <div className="editorialStats"><article><span><List/></span><div><small>Total de conteúdos</small><strong>{stats.total}</strong></div></article><article><span><GripVertical/></span><div><small>A fazer</small><strong>{stats.todo}</strong></div></article><article><span><Palette/></span><div><small>Em andamento</small><strong>{stats.progress}</strong></div></article><article><span><CalendarDays/></span><div><small>Concluídos</small><strong>{stats.completed}</strong></div></article></div>
  <section className="card editorialSection"><SectionTitle icon={<List/>} title="Tabela editorial" subtitle="Controle operacional de cada conteúdo e suas etapas"/><div className="editorialTableWrap"><table className="editorialTable"><thead><tr><th>Data</th><th>Status</th><th>Conteúdo</th><th>Headline</th>{workflow.map(([,label])=><th key={label}>{label}</th>)}<th>Formato</th><th>Referência</th><th/></tr></thead><tbody>{[...posts].sort((a,b)=>a.date.localeCompare(b.date)).map(post=>{const status=statusOf(post);return <tr key={post.id}><td><b>{formatDate(post.date)}</b></td><td><span className={`editorialStatus ${statusTone[status]}`}>{statusLabel[status]}</span></td><td><strong>{post.name}</strong></td><td className="editorialHeadline">{post.headline||'—'}</td>{workflow.map(([key,label])=><td key={key}><label className="editorialStep" title={label}><input type="checkbox" checked={post.steps[key]} onChange={event=>toggleStep(post,key,event.target.checked)}/><i/></label></td>)}<td><span className="formatBadge">{post.format}</span></td><td>{post.reference?<a className="referenceLink" href={post.reference} target="_blank" rel="noreferrer"><ExternalLink/> Abrir</a>:'—'}</td><td><div className="editorialActions"><button className="iconBtn" title="Editar" onClick={()=>{setEditing(post);setModal(true)}}><Pencil/></button><button className="iconBtn delete" title="Excluir" onClick={()=>remove(post)}><Trash2/></button></div></td></tr>})}</tbody></table>{!posts.length&&<EditorialEmpty onAdd={()=>setModal(true)}/>}</div>
  </section>
  <section className="card editorialSection"><SectionTitle icon={<LayoutGrid/>} title="Kanban de produção" subtitle="Arraste os conteúdos para atualizar o andamento"/><div className="editorialKanban">{columns.map(status=><div className={`editorialColumn ${status}`} key={status} onDragOver={event=>event.preventDefault()} onDrop={()=>movePost(status)}><header><span>{statusLabel[status]}</span><b>{posts.filter(post=>statusOf(post)===status).length}</b></header><div>{posts.filter(post=>statusOf(post)===status).map(post=><article key={post.id} draggable onDragStart={()=>setDragged(post.id)}><div><span className="postInitials">{initials(post.name)}</span><GripVertical/></div><h4>{post.name}</h4><p>{post.headline||'Sem headline definida'}</p><footer><span>{post.format}</span><time><CalendarDays/>{formatDate(post.date)}</time></footer><div className="postWorkflowProgress"><i style={{width:`${Math.round(Object.values(post.steps).filter(Boolean).length/workflow.length*100)}%`}}/></div></article>)}</div></div>)}</div>
  </section>
  <section className="card editorialSection"><div className="editorialCalendarHeader"><SectionTitle icon={<CalendarDays/>} title="Calendário editorial" subtitle="Distribuição dos conteúdos por data de publicação"/><div><button className="iconBtn" onClick={()=>setCalendarDate(new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1))}><ChevronLeft/></button><b>{calendarDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</b><button className="iconBtn" onClick={()=>setCalendarDate(new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1))}><ChevronRight/></button></div></div><EditorialCalendar date={calendarDate} posts={posts}/></section>
  {modal&&<PostModal post={editing} onClose={()=>{setModal(false);setEditing(null)}} onSave={savePost}/>} 
 </main>
}

function SectionTitle({icon,title,subtitle}:{icon:React.ReactNode;title:string;subtitle:string}){return <div className="editorialSectionTitle"><span>{icon}</span><div><h3>{title}</h3><p>{subtitle}</p></div></div>}
function EditorialEmpty({onAdd}:{onAdd:()=>void}){return <div className="editorialEmpty"><Palette/><b>Nenhum conteúdo planejado</b><span>Adicione o primeiro post desta linha editorial.</span><button className="btn secondary" onClick={onAdd}><Plus/> Adicionar conteúdo</button></div>}
function PostModal({post,onClose,onSave}:{post:EditorialPost|null;onClose:()=>void;onSave:(post:EditorialPost)=>void}){const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),now=new Date().toISOString();onSave({id:post?.id||crypto.randomUUID(),date:String(form.get('date')),name:String(form.get('name')).trim(),headline:String(form.get('headline')).trim(),format:String(form.get('format')) as EditorialFormat,reference:String(form.get('reference')).trim(),steps:post?.steps||emptySteps(),createdAt:post?.createdAt||now,updatedAt:now})};return <div className="overlay"><div className="modal editorialModal"><div className="modalHead"><div><small>LINHA EDITORIAL</small><h2>{post?'Editar conteúdo':'Novo conteúdo'}</h2><p>Cadastre as informações que acompanharão a produção.</p></div><button className="iconBtn" onClick={onClose}><X/></button></div><form className="form" onSubmit={submit}><label>Data de publicação<input name="date" type="date" required defaultValue={post?.date||dateKey(new Date())}/></label><label>Formato<select name="format" defaultValue={post?.format||'Post estático'}><option>Reels</option><option>Post estático</option><option>Carrossel</option></select></label><label className="full">Nome do post<input name="name" required autoFocus defaultValue={post?.name} placeholder="Ex.: 5 dicas para melhorar o ROAS"/></label><label className="full">Headline<input name="headline" defaultValue={post?.headline} placeholder="Título ou chamada principal do conteúdo"/></label><label className="full">Link de referência<input name="reference" type="url" defaultValue={post?.reference} placeholder="https://..."/></label><div className="editorialWorkflowPreview full"><b>Fluxo de produção</b><div>{workflow.map(([,label],index)=><span key={label}><i>{index+1}</i>{label}</span>)}</div></div><div className="formActions full"><button type="button" className="btn secondary" onClick={onClose}>Cancelar</button><button className="btn">Salvar conteúdo</button></div></form></div></div>}
function EditorialCalendar({date,posts}:{date:Date;posts:EditorialPost[]}){const first=new Date(date.getFullYear(),date.getMonth(),1),offset=(first.getDay()+6)%7,days=new Date(date.getFullYear(),date.getMonth()+1,0).getDate(),cells=Array.from({length:42},(_,index)=>{const day=index-offset+1;return day>0&&day<=days?day:null});return <div className="editorialCalendar"><div className="calendarLabels">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(label=><b key={label}>{label}</b>)}</div><div className="editorialCalendarGrid">{cells.map((day,index)=>{const key=day?`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`:'',dayPosts=posts.filter(post=>post.date===key);return <div key={index} className={!day?'outside':''}>{day&&<><span>{day}</span>{dayPosts.slice(0,3).map(post=><article className={statusOf(post)} key={post.id}><b>{post.name}</b><small>{post.format}</small></article>)}{dayPosts.length>3&&<small className="morePosts">+{dayPosts.length-3} conteúdos</small>}</>}</div>})}</div></div>}
