import {useEffect,useMemo,useState} from 'react';
import {Bell,CheckCheck,Clock3,CreditCard,FileClock,FolderKanban,Trash2,X} from 'lucide-react';
import {store} from './storage';
type Notification={id:string;title:string;description:string;type:string;read:boolean;createdAt:string};
const seed:Notification[]=[
 {id:'n1',title:'Tarefa próxima do prazo',description:'Revisar landing page vence amanhã.',type:'task',read:false,createdAt:new Date().toISOString()},
 {id:'n2',title:'Cobrança pendente',description:'Mensalidade da Fit Life aguarda pagamento.',type:'billing',read:false,createdAt:new Date(Date.now()-3600000).toISOString()},
 {id:'n3',title:'Relatório pendente',description:'O relatório da Nutrir Saúde precisa ser enviado.',type:'report',read:false,createdAt:new Date(Date.now()-7200000).toISOString()},
];
const relative=(date:string)=>{const minutes=Math.max(1,Math.round((Date.now()-new Date(date).getTime())/60000));return minutes<60?`${minutes} min atrás`:minutes<1440?`${Math.floor(minutes/60)} h atrás`:`${Math.floor(minutes/1440)} d atrás`};
export default function NotificationCenter(){const [open,setOpen]=useState(false);const [items,setItems]=useState<Notification[]>(()=>store.get('notifications',seed));const [filter,setFilter]=useState('all');useEffect(()=>{if(!localStorage.getItem('roas_notifications'))store.set('notifications',seed);const click=(event:MouseEvent)=>{if((event.target as HTMLElement).closest('button.notification'))setOpen(value=>!value)};const update=()=>setItems(store.get('notifications',seed));document.addEventListener('click',click);window.addEventListener('roas-change',update);return()=>{document.removeEventListener('click',click);window.removeEventListener('roas-change',update)}},[]);const unread=items.filter(item=>!item.read).length;useEffect(()=>{const badge=document.querySelector('.notification i');if(badge){badge.textContent=String(unread);(badge as HTMLElement).style.display=unread?'block':'none'}},[unread]);const save=(next:Notification[])=>{setItems(next);store.set('notifications',next)};const visible=useMemo(()=>filter==='unread'?items.filter(item=>!item.read):items,[items,filter]);const icon=(type:string)=>type==='billing'?<CreditCard/>:type==='report'?<FileClock/>:type==='project'?<FolderKanban/>:<Clock3/>;return open?<><button className="notificationBackdrop" aria-label="Fechar notificações" onClick={()=>setOpen(false)}/><aside className="notificationPanel"><div className="notificationHead"><div><small>CENTRAL</small><h2>Notificações</h2></div><button className="iconBtn" onClick={()=>setOpen(false)}><X/></button></div><div className="notificationTools"><div><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Todas</button><button className={filter==='unread'?'active':''} onClick={()=>setFilter('unread')}>Não lidas <span>{unread}</span></button></div><button onClick={()=>save(items.map(item=>({...item,read:true})))}><CheckCheck/> Marcar todas como lidas</button></div><div className="notificationList">{visible.map(item=><article className={item.read?'read':''} onClick={()=>save(items.map(value=>value.id===item.id?{...value,read:true}:value))}><span className={'notificationType '+item.type}>{icon(item.type)}</span><div><b>{item.title}</b><p>{item.description}</p><small>{relative(item.createdAt)}</small></div><button className="iconBtn" title="Excluir" onClick={event=>{event.stopPropagation();save(items.filter(value=>value.id!==item.id))}}><Trash2/></button></article>)}{!visible.length&&<div className="notificationEmpty"><Bell/><b>Tudo em dia</b><span>Nenhuma notificação nesta visualização.</span></div>}</div></aside></>:null}
