import {useEffect,useState} from 'react';
import {CalendarDays, GripVertical, Plus, UserRound, X} from 'lucide-react';
import {store} from './storage';
import type {Client} from './types';
type Stage='Leads captados'|'Primeiro contato'|'Em andamento'|'Reunião'|'Ciclo de acompanhamento'|'Em espera'|'Negócio fechado'|'Negócio perdido';
type Lead={id:string;name:string;contact:string;value:number;stage:Stage;source:string;nextAction:string;color:string};
const stages:Stage[]=['Leads captados','Primeiro contato','Em andamento','Reunião','Ciclo de acompanhamento','Em espera','Negócio fechado','Negócio perdido'];
const colors=['#5b36f2','#287cf0','#10a56b','#e78c12','#e8547c'];
const sample:Lead[]=[
 {id:'lead-1',name:'Odonto Prime',contact:'Mariana Lima',value:4200,stage:'Leads captados',source:'Instagram',nextAction:'Qualificar lead',color:colors[0]},
 {id:'lead-2',name:'Studio Move',contact:'Bruna Cardoso',value:2800,stage:'Primeiro contato',source:'Indicação',nextAction:'Enviar apresentação',color:colors[1]},
 {id:'lead-3',name:'Casa Alva',contact:'Lucas Prado',value:3500,stage:'Em andamento',source:'Site',nextAction:'Alinhar proposta',color:colors[2]},
 {id:'lead-4',name:'Clínica Nova',contact:'Lara Fernandes',value:4800,stage:'Reunião',source:'Google',nextAction:'Reunião hoje, 15h',color:colors[3]},
 {id:'lead-5',name:'Bela Forma Estética',contact:'Fernanda Dias',value:2200,stage:'Ciclo de acompanhamento',source:'Instagram',nextAction:'Follow-up em 2 dias',color:colors[4]},
];
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function ProspectsCRM(){const [open,setOpen]=useState(false);const [leads,setLeads]=useState<Lead[]>(()=>store.get('prospects',sample));const [modal,setModal]=useState(false);const [dragged,setDragged]=useState<string|null>(null);
 useEffect(()=>{if(!localStorage.getItem('roas_prospects'))store.set('prospects',sample);const listener=(e:MouseEvent)=>{const el=e.target as HTMLElement;const button=el.closest('button');if(button?.textContent?.trim()==='Prospects')setOpen(true)};document.addEventListener('click',listener);return()=>document.removeEventListener('click',listener)},[]);
 const save=(next:Lead[])=>{setLeads(next);store.set('prospects',next)};const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);save([{id:crypto.randomUUID(),name:String(f.get('name')),contact:String(f.get('contact')),value:Number(f.get('value')),stage:'Leads captados',source:String(f.get('source')),nextAction:'Fazer primeiro contato',color:colors[leads.length%colors.length]},...leads]);setModal(false)};
 const move=(stage:Stage)=>{if(dragged)save(leads.map(lead=>lead.id===dragged?{...lead,stage}:lead));setDragged(null)};
 return <>{open&&<div className="crmOverlay"><section className="crmBoard"><div className="crmHead"><div><small>CLIENTES · PROSPECTS</small><h2>Mini CRM comercial</h2><p>{leads.length} oportunidades · {money(leads.filter(l=>!['Negócio perdido','Negócio fechado'].includes(l.stage)).reduce((s,l)=>s+l.value,0))} em negociação</p></div><div><button className="btn" onClick={()=>setModal(true)}><Plus/> Novo lead</button><button className="iconBtn crmClose" onClick={()=>setOpen(false)}><X/></button></div></div><div className="crmColumns">{stages.map(stage=>{const cards=leads.filter(lead=>lead.stage===stage);return <div className={'crmColumn '+stage.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z]/g,'-')} onDragOver={e=>e.preventDefault()} onDrop={()=>move(stage)}><header><b>{stage}</b><span>{cards.length}</span></header><div className="crmCards">{cards.map(lead=><article className="leadCard" draggable onDragStart={()=>setDragged(lead.id)}><div className="leadTop"><i style={{background:lead.color}}>{lead.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><GripVertical/></div><h3>{lead.name}</h3><p><UserRound/>{lead.contact}</p><strong>{money(lead.value)}</strong><footer><span>{lead.source}</span><small><CalendarDays/>{lead.nextAction}</small></footer></article>)}</div><button className="addLead" onClick={()=>setModal(true)}>＋ Adicionar lead</button></div>})}</div></section></div>}{modal&&<div className="overlay"><div className="modal crmModal"><div className="modalHead"><div><small>NOVO LEAD</small><h2>Adicionar oportunidade</h2></div><button className="iconBtn" onClick={()=>setModal(false)}><X/></button></div><form className="form" onSubmit={add}><label>Empresa<input name="name" required autoFocus placeholder="Nome da empresa"/></label><label>Contato<input name="contact" required placeholder="Nome do contato"/></label><label>Valor estimado<input name="value" type="number" min="0" required/></label><label>Origem<select name="source"><option>Instagram</option><option>Site</option><option>Indicação</option><option>Google</option><option>WhatsApp</option></select></label><div className="formActions full"><button type="button" className="btn secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="btn">Adicionar ao CRM</button></div></form></div></div>}</>}
