import {useEffect,useState} from 'react';
import {Download, RotateCcw, Save} from 'lucide-react';
import {store} from './storage';
import ServicesManager from './ServicesManager';

const tabs=['Geral','Agência','Serviços','Aparência','Notificações','Dados','Backup'];
export default function SettingsPage(){
  const [tab,setTab]=useState('Geral');
  const [theme,setTheme]=useState(localStorage.getItem('roas_theme')||'light');
  const [sidebarOpen,setSidebarOpen]=useState(localStorage.getItem('roas_sidebar_open')!=='false');
  const [saved,setSaved]=useState(false);
  useEffect(()=>{const apply=(value:string)=>{const resolved=value==='system'?(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value;document.documentElement.dataset.theme=resolved};apply(theme);const media=window.matchMedia('(prefers-color-scheme: dark)');const listener=()=>theme==='system'&&apply(theme);media.addEventListener('change',listener);return()=>media.removeEventListener('change',listener)},[theme]);
  const saveAgency=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);store.set('agency_settings',Object.fromEntries(form));setSaved(true);setTimeout(()=>setSaved(false),2200)};
  const download=()=>{const values=Object.fromEntries(Object.entries(localStorage).filter(([key])=>key.startsWith('roas_')));const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(values,null,2)],{type:'application/json'}));link.download='backup-roas.json';link.click();URL.revokeObjectURL(link.href)};
  return <main><section className="card settings"><div className="settingsNav">{tabs.map(label=><button key={label} className={tab===label?'active':''} onClick={()=>setTab(label)}>{label}</button>)}</div><div className="settingsBody">
    {tab==='Geral'&&<><h2>Configurações gerais</h2><p>Escolha como sua operação será apresentada no sistema.</p><form className="form" onSubmit={saveAgency}><label>Nome da agência<input name="agencyName" defaultValue="Agência ROAS"/></label><label>E-mail<input name="email" type="email" defaultValue="contato@agenciaroas.com.br"/></label><label>Telefone<input name="phone" defaultValue="(11) 99999-0000"/></label><label>Site<input name="website" defaultValue="www.agenciaroas.com.br"/></label><label>Moeda<select name="currency"><option>BRL — Real brasileiro</option><option>USD — Dólar americano</option></select></label><label>Fuso horário<select name="timezone"><option>America/Sao_Paulo</option><option>UTC</option></select></label><div className="formActions full"><button className="btn"><Save/> Salvar alterações</button></div></form>{saved&&<div className="inlineSuccess">✓ Configurações salvas neste navegador.</div>}</>}
    {tab==='Agência'&&<><h2>Perfil da agência</h2><p>Informações institucionais exibidas em relatórios e documentos.</p><form className="form" onSubmit={saveAgency}><label>Razão social<input name="legalName" defaultValue="Agência ROAS Ltda."/></label><label>CNPJ<input name="taxId" placeholder="00.000.000/0001-00"/></label><label className="full">Endereço<input name="address" placeholder="Rua, número, cidade e estado"/></label><div className="formActions full"><button className="btn"><Save/> Salvar perfil</button></div></form></>}
    {tab==='Serviços'&&<ServicesManager/>}
    {tab==='Aparência'&&<><h2>Aparência</h2><p>Defina a preferência visual do sistema.</p><div className="themeChoices">{['light','dark','system'].map(value=><button key={value} className={theme===value?'active':''} onClick={()=>{setTheme(value);localStorage.setItem('roas_theme',value)}}>{value==='light'?'☀️ Tema claro':value==='dark'?'🌙 Tema escuro':'💻 Sistema'}</button>)}</div><p className="settingsHint">A mudança é aplicada imediatamente e fica salva neste navegador.</p><hr/><h2>Menu lateral</h2><p>Escolha como o menu deve aparecer ao acessar o sistema.</p><div className="sidebarPreference"><div><b>Menu expandido</b><span>Exibe os ícones e os nomes de todas as páginas.</span></div><button type="button" role="switch" aria-checked={sidebarOpen} className={'switchControl '+(sidebarOpen?'on':'')} onClick={()=>{const next=!sidebarOpen;setSidebarOpen(next);localStorage.setItem('roas_sidebar_open',String(next));window.dispatchEvent(new CustomEvent('roas-sidebar-toggle',{detail:next}))}}><i/></button></div><div className="sidebarPreview"><div className={sidebarOpen?'previewMenu open':'previewMenu'}><span>R</span>{sidebarOpen&&<><b>Dashboard</b><b>Clientes</b><b>Projetos</b></>}</div><p>{sidebarOpen?'O menu ficará aberto por padrão.':'O menu ficará recolhido, mostrando apenas os ícones.'}</p></div></>}
    {tab==='Notificações'&&<><h2>Notificações</h2><p>Escolha os alertas que deseja acompanhar.</p><div className="toggleList">{['Tarefas próximas do prazo','Tarefas atrasadas','Novo pagamento recebido','Cobrança vencida','Relatório pendente'].map((label,index)=><label key={label}><span><b>{label}</b><small>Receber alerta no centro de notificações</small></span><input type="checkbox" defaultChecked={index<4}/></label>)}</div></>}
    {tab==='Dados'&&<><h2>Dados locais</h2><p>Exporte uma cópia dos dados ou restaure a demonstração.</p><div className="dangerRow"><button className="btn secondary" onClick={download}><Download/> Exportar backup</button><button className="btn secondary" onClick={()=>{if(confirm('Restaurar todos os dados demonstrativos?')){store.reset();location.reload()}}}><RotateCcw/> Restaurar demonstração</button></div></>}
    {tab==='Backup'&&<><h2>Backup</h2><p>O sistema salva automaticamente no navegador deste dispositivo.</p><div className="backupBox"><b>Backup local ativo</b><span>Dados protegidos no localStorage do navegador.</span><button className="btn" onClick={download}><Download/> Baixar backup agora</button></div></>}
  </div></section></main>
}
